### ISSUE TITLE
Support xref or caller functionality

### ISSUE THREAD

**Issue by dgtized** [clojure-emacs/cider-nrepl#103]
I took a brief look at the old swank code, and found this: https://github.com/technomancy/swank-clojure/blob/master/src/swank/commands/xref.clj. If I read correctly it's naively grepping the source of all functions to see if they call a particular function. Should we revive support for this in cider, and can we do better than simply grepping?

**Comment by bbatsov** [comment]
Closing in favour of merging @benedekfazekas & @expez's work instead.
