### ISSUE TITLE
cider-nrepl breaks for the JDK9 preview.

### ISSUE THREAD

**Issue by jaccarmac** [clojure-emacs/cider-nrepl#104]
https://github.com/clojure-emacs/cider-nrepl/blob/d8f6da05305ebec988e64d5b6586ecb9d5fc42d6/src/cider/nrepl/middleware/util/java/parser.clj#L62 breaks.

The documentation for the class is somewhat sparse, but apparently com.sun.tools.javadoc.JavadocEnter does not have an instance0 method any more. Not sure if it's a regression or a feature yet, and will keep this updated as JDK9 matures.

**Comment by jaccarmac** [comment]
This issue appears to be resolved as of 0.9.0-SNAPSHOT.

**Comment by bbatsov** [comment]
More likely it was fixed in the JDK as I don't think we've changed anything
related.

On Monday, January 5, 2015, Jacob MacDonald <notifications@github.com>
wrote:

> This issue appears to be resolved as of 0.9.0-SNAPSHOT.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider-nrepl/issues/104#issuecomment-68733844>
> .
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by jaccarmac** [comment]
Copy that. Closing until we see another regression.
