### ISSUE TITLE
Pagination when inspecting long sequences

### ISSUE THREAD

**Issue by alexander-yakushev** [clojure-emacs/cider-nrepl#123]
It would be very helpful if when tried to inspect a long sequential data cider-inspect displayed it in chunks. Right now inspector tries to dump the whole sequence, so it fails to display anything at all. That's why I have to do things like `(take 10 ...)` every time I want to inspect a large collection, which kinda eliminates the purpose of all-round inspector.

Other possible solution would be to show small chunk of elements by default (say, 20) and then be able to expand the whole collection.

I can implement it myself if it is something that others would like to have as well.

**Comment by bbatsov** [comment]
@alexander-yakushev Ping :-)

**Comment by alexander-yakushev** [comment]
I gonna get to it... someday:)

**Comment by bbatsov** [comment]
@Malabarba this is somewhat related to your most recent PR. Given the link between the debugger and the inspector maybe you can look into this as well.

**Comment by Malabarba** [comment]
If by "related" you mean that the debugger calls the inspector... :-)

It seems there's an acute pandemic of `out-of-timitis` spreading through the cider contributors.

**Comment by bbatsov** [comment]
I'm just trying jedi mind tricks to get the ball rolling on certain stale tasks. From time to time this even works. ;-)

**Comment by alexander-yakushev** [comment]
Feature is merged, everyone is happy.
