### ISSUE TITLE
Could not locate rewrite_clj/node__init.class or rewrite_clj/node.clj

### ISSUE THREAD

**Issue by jcf** [clojure-emacs/cider-nrepl#146]
Hi there!

Tried to start up a REPL earlier today to be presented with this:

```
clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate rewrite_clj/node__init.class or rewrite_clj/node.clj on classpath: , compiling:(cljfmt/core.clj:1:1)
 at clojure.lang.Compiler.load (Compiler.java:7142)
    clojure.lang.RT.loadResourceScript (RT.java:370)
    clojure.lang.RT.loadResourceScript (RT.java:361)
    clojure.lang.RT.load (RT.java:440)
    clojure.lang.RT.load (RT.java:411)
    clojure.core$load$fn__5066.invoke (core.clj:5641)
    clojure.core$load.doInvoke (core.clj:5640)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invoke (core.clj:5446)
    clojure.core$load_lib$fn__5015.invoke (core.clj:5486)
    clojure.core$load_lib.doInvoke (core.clj:5485)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$load_libs.doInvoke (core.clj:5524)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$require.doInvoke (core.clj:5607)
    clojure.lang.RestFn.invoke (RestFn.java:457)
    cider.nrepl.middleware.format$eval1695$loading__4958__auto____1696.invoke (format.clj:1)
    cider.nrepl.middleware.format$eval1695.invoke (format.clj:1)
```

[Full stacktrace here][1].

Looks like introduction of cljfmt in a1482cb might be the source as commenting out `cider/cider-nrepl` makes the error go away.

I've explicitly added cljfmt to my [profiles.clj][] and can require `rewrite-clj.node` in a REPL, but I can't run `lein cljfmt check`.

I'd love to rollback to a stable version but with everything being a snapshot it's kinda impossible. If there's anything I can do to expedite a fix please let me know.

The issue occurs with both JDK 1.7 and 1.8 on OS 10.10. I'm going to dig a little more into James' cljfmt now to see if I need to open an issue/PR over there.

[1]: https://gist.github.com/jcf/62656682398aa25cf1e1
[profiles.clj]: https://github.com/jcf/dotfiles/commit/851e578092b3f438d0ef6cfc9b5595cf02dea3ba

**Comment by bbatsov** [comment]
Guess you should report this upstream. It might also be a dependency conflict if something else in your project is using an older version of `clj-rewrite`.

**Comment by expez** [comment]
@jcf got `lein-ancient` installed?

**Comment by jcf** [comment]
@bbatsov I'm trying to isolate and reproduce before opening an issue upstream.

And…

@expez commenting out `lein-ancient` did it. :smile:

**Comment by jcf** [comment]
[Upgrading][] `lein-ancient` to 0.6.2 fixes everything. Thank you for your help chaps! Really appreciate it.

[Upgrading]: https://github.com/jcf/dotfiles/commit/f77bf6361317dce4b19317d5f7b3e60174e24790

**Comment by bbatsov** [comment]
Now you'll understand why https://github.com/clojure-emacs/cider-nrepl/issues/143 is very important :-)

**Comment by jcf** [comment]
@bbatsov I most certainly do. Are you going to start shipping an uberjar? :wink:

**Comment by bbatsov** [comment]
No idea. I just know we have to do something, otherwise we'll always have
problems like this one...

On 9 February 2015 at 18:31, James Conroy-Finn <notifications@github.com>
wrote:

> @bbatsov <https://github.com/bbatsov> I most certainly do. Are you going
> to start shipping an uberjar? [image: :wink:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider-nrepl/issues/146#issuecomment-73539650>
> .
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by glittershark** [comment]
Wonderful - a Lein plugin for discovering old versions of dependencies broke my app because I was depending on an old version of it.

**Comment by drusellers** [comment]
@glittershark :+1:
