### ISSUE TITLE
Addition of cljfmt causing dependency issues

### ISSUE THREAD

**Issue by marknsikora** [clojure-emacs/cider-nrepl#148]
The addition of the cljfmt dependency in a1482cba0864f556fa5491ad4665fa8e4ba7c75e pulls in an rather old version of the closure compiler. This breaks all my projects using protobuf since they need a newer version than what gets pulled in. The issue originates with `fast-zip` which depends on an old version of `com.cemerick/austin`.

I'll be looking into this over the weekend to see if I can submit a pull request to `fast-zip` to update. But for the time being I think this commit should be reverted. 

```
 [cider/cider-nrepl "0.9.0-20150208.163350-4"]
   [cljfmt "0.1.7" :exclusions [[org.clojure/clojure]]]
     [rewrite-clj "0.4.11"]
       [fast-zip "0.5.2" :exclusions [[org.clojure/clojure]]]
         [com.cemerick/austin "0.1.5"]
           [com.cemerick/piggieback "0.1.3"]
           [org.clojure/clojurescript "0.0-2227"]
             [com.google.javascript/closure-compiler "v20131014"]
               [args4j "2.0.16"]
               [com.google.code.findbugs/jsr305 "1.3.9"]
               [com.google.guava/guava "15.0"]
               [com.google.protobuf/protobuf-java "2.4.1"]
...
```

**Comment by bbatsov** [comment]
Related - https://github.com/xsc/rewrite-clj/issues/26 and https://github.com/clojure-emacs/cider-nrepl/issues/143

**Comment by bbatsov** [comment]
Quick update - `fast-zip` was removed as a dep of `rewrite-clj` and we just need a new release of `cljfmt` to solve this once and for all.
