### ISSUE TITLE
Inspector does not support ClojureScript

### ISSUE THREAD

**Issue by cichli** [clojure-emacs/cider-nrepl#152]
Currently the inspector calls Clojure `eval` directly (see [here](https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/inspect.clj#L11)). I think we can modify it to instead rely on regular eval ops, and use the resulting `:value` slot (we should ensure that we get its value before `pr-values` transforms it into a string).

I'll take a look at doing this over the weekend.

**Comment by bbatsov** [comment]
Making the inspector portable would be amazing!

**Comment by cichli** [comment]
Forgot to mention this one in the commit message in #164 :blush:
