### ISSUE TITLE
:complete op to optionally return info for each var?

### ISSUE THREAD

**Issue by laurentpetit** [clojure-emacs/cider-nrepl#176]
Hello,

I'm contemplating moving the Counterclockwise "server" code to cider-nrepl. Currently toying with it, but I already am able to use the :complete op instead of CCW's own code.

What's missing is that currently CCW returns not only a vector of var Strings, but a vector of metadata for each var, removing the need to do N+1 calls.

Granted, this is far more data to transport than just the current vector of Strings. I haven't done any benchmark yet.

Question is: would you find the idea of optionally returning a vector with the vars info acceptable?

Maybe you already know this is not feasible in practice because you already tried it or the function to return individual var metadata is too costly to call it ahead of time, etc. ?

**Comment by bbatsov** [comment]
> I'm contemplating moving the Counterclockwise "server" code to cider-nrepl. Currently toying with it, but I already am able to use the :complete op instead of CCW's own code.

That'd be awesome. Despite the name `cider-nrepl` is mostly Emacs agnostic and I'd love to see more tools using it (for far vim-fireplace does so and I hear LT is contemplating its usage).

> What's missing is that currently CCW returns not only a vector of var Strings, but a vector of metadata for each var, removing the need to do N+1 calls.

Are we talking about all the var metadata here or some specific metadata? Did you notice the changes in `cider-nrepl` 0.9 - we now actually return a vector of completion candidate info - e.g. a var's name, type, ns, etc. 

I guess you need all the metadata for some doc popup you have to display alongside the currently selected candidate, right?

> Maybe you already know this is not feasible in practice because you already tried it or the function to return individual var metadata is too costly to call it ahead of time, etc. ?

Right now we call `var-info` when needed - guess the overhead of an extra op call and the overhead of encoding/decoding all the metadata would be more or less the same. So far it hasn't been a performance issue and we didn't really need to explore alternative solutions.

//cc @alexander-yakushev

**Comment by cichli** [comment]
Hi Laurent, on master we now actually return a map for each candidate with just enough data to annotate it in a completion popup - a string representing its type (function, macro, var, etc.) and its namespace (if the candidate is not already namespace-qualified). I'm sure an option for also including the full metadata (or presumably just what would be the result of an `info` request for the candidate) in this map would be fine to have. Alternatively, any suggestion for extra data that would be useful to include in this map would also be welcome (arglists is at least one I can think of).

FWIW I think decoding that much data emacs-side every time completion is initiated would be too much, but in your case the client may be able to handle it. Are the client and the server in the same JVM process in CCW?

**Comment by laurentpetit** [comment]
2015-03-29 20:21 GMT+02:00 Bozhidar Batsov <notifications@github.com>:

> I'm contemplating moving the Counterclockwise "server" code to
> cider-nrepl. Currently toying with it, but I already am able to use the
> :complete op instead of CCW's own code.
>
> That'd be awesome. Despite the name cider-nrepl is mostly Emacs agnostic
> and I'd love to see more tools using it (for far vim-fireplace does so and
> I hear LT is contemplating its usage).
>
Yes, I have looked at the code, and indeed seen that it is a valid
candidate for adoption. I just don't know how much a moving target that
would be to follow. No offense, but for instance Leiningen has been quite a
moving target, with some functions CCW depended upon changing names, some
features moving around, and if I could send a word to my former self, I
would have advised myself to treat it more like a black box.
I don't have enough experience with cider-repl codebase to appreciate
whether the "op" parts of it, and the associated (currently implicit rather
than explicit) "data API" is stable enough.

 What's missing is that currently CCW returns not only a vector of var
> Strings, but a vector of metadata for each var, removing the need to do N+1
> calls.
>
> Are we talking about all the var metadata here or some specific metadata?
> Did you notice the changes in cider-nrepl 0.9 - we now actually return a
> vector of completion candidate info - e.g. a var's name, type, ns, etc.
>
> I guess you need all the metadata for some doc popup you have to display
> alongside the currently selected candidate, right?
>
That's exactly that. I'll take a close look at v0.9, since it may well
provide what I'm after!


>  Maybe you already know this is not feasible in practice because you
> already tried it or the function to return individual var metadata is too
> costly to call it ahead of time, etc. ?
>
> Right now we call var-info when needed - guess the overhead of an extra
> op call and the overhead of encoding/decoding all the metadata would be
> more or less the same. So far it hasn't been a performance issue and we
> didn't really need to explore alternative solutions.
>
Roger that. I have created a branch locally to also explore what changes I
could do to CCW to go a step in cider-nrepl's direction. I will also try to
collect some informal performance data as well.


> //cc @alexander-yakushev <https://github.com/alexander-yakushev>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider-nrepl/issues/176#issuecomment-87452683>
> .
>



-- 
Laurent Petit

**Comment by laurentpetit** [comment]
2015-03-29 20:22 GMT+02:00 Michael Griffiths <notifications@github.com>:

> Hi Laurent, on master we now actually return a map for each candidate with
> just enough data to annotate it in a completion popup - a string
> representing its type (function, macro, var, etc.) and its namespace (if
> the candidate is not already namespace-qualified). I'm sure an option for
> also including the full metadata (or presumably just what would be the
> result of an info request for the candidate) in this map would be fine to
> have. Alternatively, any suggestion for extra data that would be useful to
> include in this map would also be welcome (arglists is at least one I can
> think of).
>
I wasn't aware of these recent enhancements. Will work from master and see
how far I can go! Exciting times!!

> FWIW I think decoding that much data emacs-side every time completion is
> initiated would be too much, but in your case the client may be able to
> handle it. Are the client and the server in the same JVM process in CCW?
>
No, client & server aren't in the same JVM process. The project's JVM
process creation is delegated to leiningen(*) with just some additional
tweaks to the project's map through update & al leiningen embedded
plugins(**). The fact that leiningen always will report the nREPL url in
the nrepl://server:port format is then leverage to automatically open a
repl client on behalf of the user. Nothing too magic (I hope), just some
repetitive task automated.

(*): there is also a non-leiningen managed mode, which just uses dependency
info from leiningen, but does not use leiningen itself to start the process
(pro = way faster to start a new project process ; con = more advanced
leiningen configuration & plugins are not involved during the project
process creation)

(**): also, to provide better cross-platform support (think Windows), CCW
does not use the .sh / .bat shell scripts, but creates itself the leiningen
java process command line (this involves, from time to time, re-reading the
lein.sh script to follow enhancements. Also, for the time being, the
trampoline behavior has not been reproduced).


>  —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider-nrepl/issues/176#issuecomment-87452925>
> .
>



-- 
Laurent Petit

**Comment by alexander-yakushev** [comment]
Typical grumpy comment from me: I would rather not pack all vars' metadata in every single query response. There is a noticeable delay in completion on Android, partly because TCP connection over adb is godawfully slow. Sending all metadata would make it significantly worse.

Still, we return maps now, not strings, so the extension mechanism is already there. For example, if CCW  wants to show arglists for functions immediately with the completion candidates — I'm OK with adding that to the current response. Docstrings on the other hand don't make sense to have immediately as there is no way to show them all at the same time. And I suspect that the overhead from an extra call will be lower than from having a quite massive extra data for each candidate.

That being said, I'd follow the approach where the completion backend sends only the information that the frontend can adequately use, and not the one where we send all the stuff and let the frontend sort it out later.

**Comment by laurentpetit** [comment]
2015-03-29 22:57 GMT+02:00 Alexander Yakushev <notifications@github.com>:

> Typical grumpy comment from me: I would rather not pack all vars' metadata
> in every single query response. There is a noticeable delay in completion
> on Android, partly because TCP connection over adb is godawfully slow.
> Sending all metadata would make it significantly worse.
>
> Still, we return maps now, not strings, so the extension mechanism is
> already there. For example, if CCW wants to show arglists for functions
> immediately with the completion candidates — I'm OK with adding that to the
> current response. Docstrings on the other hand don't make sense to have
> immediately as there is no way to show them all at the same time. And I
> suspect that the overhead from an extra call will be lower than from having
> a quite massive extra data for each candidate.
>
> That being said, I'd follow the approach where the completion backend
> sends only the information that the frontend can adequately use, and not
> the one where we send all the stuff and let the frontend sort it out later.
>
I totally get the issue with Android. I also always had had those concerns
wrt remote connections, even though those have not yet been reported as
causing problem ("yet" : maybe it's just a matter of time and of maturity
of CCW user's development workflows).

The new version sending maps instead of plain strings will probably be
sufficient.
I don't have all the Eclipse framework in mind right now. I recall that
some time ago, I had implemented a kind of lazy loading for docstrings
(when the focus is on a particular completion entry in the popup), and that
I switched back to getting everything upfront when I switched the
implementation to plain clojure instead of java.
I can probably easily switch back to lazy loading if required. If not, I'll
go back here with ideas to make the list of per-entry returned keys more "a
la carte" (what about an optional additional query key listing the keys we
want?)

—
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider-nrepl/issues/176#issuecomment-87474698>
> .
>



-- 
Laurent Petit

**Comment by alexander-yakushev** [comment]
> If not, I'll go back here with ideas to make the list of per-entry returned keys more "a la carte" (what about an optional additional query key listing the keys we want?)

Yes, this is also possible. Although the list of possible keys has to be known upfront, because I'll have to handle each manually. So you would still have to come up first with which additional information you need for candidates, I will implement it.
