### ISSUE TITLE
using 0.9.0alpha

### ISSUE THREAD

**Issue by imtayadeway** [clojure-emacs/cider-nrepl#178]
in Emacs, doing `M-x cider-version` returns 0.9.0alpha.

I updated my ~/.lein/profiles.clj:

```clojure
{:user {:plugins [[cider/cider-nrepl "0.9.0alpha"]]}}
```

when i jack in, however, i get an error saying that the artifact could not be found. am i doing something wrong?

cheers!

**Comment by cichli** [comment]
It's `0.9.0-SNAPSHOT` for the clojure dep.

**Comment by imtayadeway** [comment]
that does the trick. thanks!
