### ISSUE TITLE
Integration tests for ClojureScript/piggieback

### ISSUE THREAD

**Issue by cichli** [clojure-emacs/cider-nrepl#179]
I think the best way will be to have the piggieback-specific tests in a separate directory, e.g.

* `test\common` for fixtures etc. that should be shared between both kinds of test
* `test\clj` for the existing tests
* `test\cljs` for the new tests

Then we can set `test-paths` accordingly in each of the test profiles.

One obstacle is that ClojureScript doesn't support Java 1.6 anymore - perhaps it's time to remove that job from Travis? Last public update was [over two years ago](http://www.oracle.com/technetwork/java/eol-135779.html#Java6-end-public-updates) FWIW.

**Comment by bbatsov** [comment]
> One obstacle is that ClojureScript doesn't support Java 1.6 anymore - perhaps it's time to remove that job from Travis? Last public update was over two years ago FWIW.

Maybe. On the other hand it seems people are still using 1.6 https://cognitect.wufoo.com/reports/state-of-clojure-2014-results/ to some extent. 

I can live without it in Travis, though.

**Comment by cichli** [comment]
Well I'll at least try and find a clean way to only run the tests on the 1.7 & 1.8 JDKs.
