### ISSUE TITLE
Find resource crashes when called without resource at point

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider-nrepl#180]
When the mw is called without a resource at point this stacktrace is produced:

```
ERROR: Unhandled REPL handler exception processing message {:op resource, :name [], :id 2794}
java.lang.ClassCastException: clojure.lang.PersistentVector cannot be cast to java.lang.String
	at clojure.java.io$resource.invoke(io.clj:440)
	at clojure.java.io$resource.invoke(io.clj:439)
	at cider.nrepl.middleware.resource$resource_path.invoke(resource.clj:8)
	at cider.nrepl.middleware.resource$resource_reply.invoke(resource.clj:16)
```

and emacs hangs while the msg times out.

**Comment by bbatsov** [comment]
Ah, fuck. Another bencode issue - `nil` is represented as `[]` on the Clojure side (because it's both `nil` and `()` in Emacs Lisp), which is causing all sorts of annoyances.

**Comment by bbatsov** [comment]
On a related note - we should have some Emacs-side validation for request with params. Clearly we shouldn't have sent anything in the problematic scenario in the first place.

**Comment by cichli** [comment]
Yeah, after the recent changes, calling `cider-find-resource` with nothing at point actually sends an empty string, which returns something unexpected:

```
(--->
  op  "resource"
  name  ""
  id  "69"
)
(<-
  id  "69"
  resource-path  "/Users/griffithsm/clojure/cider-nrepl/test/common/"
  session  "62399c3f-fdbc-40f2-adb4-a7b01176d356"
  status  ("done")
)
```

Guess we should just error if `name` is nil or "".

**Comment by bbatsov** [comment]
Yep.

On Sunday, April 26, 2015, Michael Griffiths <notifications@github.com>
wrote:

> Yeah, after the recent changes, calling cider-find-resource with nothing
> at point actually sends an empty string, which returns something unexpected:
>
> (--->
>   op  "resource"
>   name  ""
>   id  "69"
> )
> (<-
>   id  "69"
>   resource-path  "/Users/griffithsm/clojure/cider-nrepl/test/common/"
>   session  "62399c3f-fdbc-40f2-adb4-a7b01176d356"
>   status  ("done")
> )
>
> Guess we should just error if name is nil or "".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider-nrepl/issues/180#issuecomment-96357809>
> .
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by cichli** [comment]
Done clojure-emacs/cider@ce1c2f51fcf2fded72fe97a78bfd87fb92eb7bad
