### ISSUE TITLE
Use a different slot than `out` in pprint middleware

### ISSUE THREAD

**Issue by cichli** [clojure-emacs/cider-nrepl#200]
Currently, we bind `*out*` to the nREPL session's `*out*` when printing - see [here](https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/pprint.clj#L15). This unfortunately means it's not possible for a client to differentiate between actual printed output and the result of evaluations - for example to send them to different buffers, or to syntax highlight one but not the other.

We can instead bind `*out*` to a new `PrintWriter` created by [`clojure.tools.nrepl.middleware.session/session-out`](https://github.com/clojure/tools.nrepl/blob/master/src/main/clojure/clojure/tools/nrepl/middleware/session.clj#L26) that uses a different slot. This will mean the result is still streamed back, and the client can decide whether to render the result as it arrives or accumulate it - we should also send some sentinel message after printing each value in case multiple forms are being evaluated.

Client-side we can modify `nrepl-make-response-handler` to treat the new slot as if it were `out` for now, but this will let us solve clojure-emacs/cider#943 eventually.

Thoughts? @laurentpetit will this suffice for differentiating between printed output and evaluation results in CCW?

**Comment by laurentpetit** [comment]
Indeed, this is 'spot on' and should totally allow counterclockwise to use pprint with no visual regression for the user.
