### ISSUE TITLE
Inject version info in session description

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider-nrepl#202]
This is possible in recent nREPL releases https://github.com/clojure/tools.nrepl/commit/f95f2be94c2e43e61f8b7464978216787194490d

Guess we just have to add some version middleware. This will save us from having to use eval to get the version, which is not a big issue, but is definitely not ideal. Down the road we can inject even more info in the session description.

**Comment by bbatsov** [comment]
@sanjayl if you're ever wondering what to do next I'd suggest tackling this. It's pretty simple, but I couldn't find time for it for 1 year...

**Comment by sanjayl** [comment]
Sounds good, will take a look at this next

**Comment by bbatsov** [comment]
Fixed in #334.
