### ISSUE TITLE
Clojure 1.4 support broken

### ISSUE THREAD

**Issue by tsmacdonald** [clojure-emacs/cider-nrepl#215]
[This commit](https://github.com/clojure-emacs/cider-nrepl/commit/c24faedbc83255f9f007da80799ff6c8ed608bd3) uses a `some->`, which breaks support for Clojure 1.4 (believe it or not, some of us in industry are still stuck there :crying_cat_face: ). Is there interest in removing it? Would it be helpful if I made a PR for it?

Thanks!

**Comment by tsmacdonald** [comment]
In February cider-nrepl also started using an EDN reader, which is not available in Clojure 1.4 either. I guess it's just over. We'll look into using an older version of Cider and cider-nrepl.

**Comment by bbatsov** [comment]
Yep, we decided to support only Clojure 1.5+. Btw, what's holding you back to Clojure 1.4? 

P.S. A manageable workaround for you would be to fork the current version of the middleware, strip everything new from it and just publish it under a different name to `clojars`.
