### ISSUE TITLE
Add instrumentation for certain data structures

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider-nrepl#217]
There are 3 form types which we don't instrument in the debugger. In order of importance:

- [x] Maps, because the order in which they're written doesn't coincide with the order in which they're read, so we can't tell Emacs the position of a given sexp.
- [x] Function literals `#(inc %)`, because the reader returns them as a `fn*`. It would be simple to do special handling for `fn*` forms, but then, should we assume that any `fn*` came from a `#()`? Probably not, in which case we need to hack into the reader to indicate where each `fn*` came from.
- [ ] Sets, same reason as maps.

**Comment by bbatsov** [comment]
> what are these called?

(Lambda) Function literals.

**Comment by Malabarba** [comment]
1. As discussed on gitter, one option for the map (and set) is to have a `#dbg` reader macro in `*data-readers*`, and inject `#dbg` (before each of these special structures) into the `eval` string before it is read by the reader.
   This would inadvertently insert `#dgb` in strings containing `{`, but then, the instrumenter already goes through every form returned by the reader, so it could just as well remove any left-over `#dbg`s inside strings.

2. A second option is to use our own reader, that fallsback on the regular `read-string` for everything except these special structures. The tricky part for me is how to do the recursion without having to write an entire parser. That is, we need a way to tell `read-string` to read the next data structure while calling our own reader on the elements of the collection.

**Comment by Malabarba** [comment]
With PR #222, function literals are solved and maps are mostly solved.
Unless someone has a genius idea on how to handle sets, I'll mark this as closed. I don't think they're too important anyway, most uses of sets I see are for storing constant data.

**Comment by bbatsov** [comment]
Let's close this.
