### ISSUE TITLE
cider-nrepl startup time

### ISSUE THREAD

**Issue by laurentpetit** [clojure-emacs/cider-nrepl#218]
On my laptop
- it takes ~30-35 secs to launch a jvm with nrepl+the default cider-nrepl handler (without involving lein).
- as a comparison point, with the default nrepl handler, it takes ~8 secs (still without involving lein)
- and it takes a little more than 1 min if use leiningen configured with cider-nrepl plugin.

This probably bears investigation to see where all the startup time is spent

**Comment by expez** [comment]
@laurentpetit Just to be sure, this was with cider-nrepl only and not also refactor-nrepl on the classpath?

**Comment by expez** [comment]
> lein repl  9.36s user 0.40s system 100% cpu 9.676 total

with

This was in cider-nrepl itself
> lein repl  4.19s user 0.19s system 60% cpu 7.298 total

without

**Comment by vspinu** [comment]
Does anyone know why projects with lein are loaded twice during startup? Is this a lein thing or could be dealt with on cider side? 

I am plugging prns here and there and seeing 

```clj
Warning: Clojure is excluded, assuming an appropriate fork (Clojure 1.7 or later) is provided.
stacktrace loaded
loading debugger
loaded cider-nrepl: 1.992
Warning: Clojure is excluded, assuming an appropriate fork (Clojure 1.7 or later) is provided.
stacktrace loaded
loading debugger
loaded cider-nrepl: 0.912
```

**Comment by bbatsov** [comment]
Likely something to do with https://stackoverflow.com/questions/27339206/why-does-leiningen-keep-its-own-jvm-running

**Comment by vspinu** [comment]
Interestingly, if run from `cider-nrepl` project, one of them loads from local `.m2/` repo and the other from the project itself. This might result in confusing errors if the two versions become desynchronized.

**Comment by bbatsov** [comment]
I guess we can close this now that #438 has been merged.
