### ISSUE TITLE
Add root-cause to exceptions in err-info

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider-nrepl#225]
As mentioned [here](https://github.com/Malabarba/cider-nrepl/commit/31ca7e12f402edf42e51516675392444bc3c9d18#commitcomment-11976122). Do something [like this](https://github.com/Malabarba/cider-nrepl/commit/31ca7e12f402edf42e51516675392444bc3c9d18#diff-0d65c570bef3dbf4640690a252e06f28R155).

**Comment by bbatsov** [comment]
Indeed. Let's hope we'll manage to squeeze this in 0.10.

**Comment by bbatsov** [comment]
You'll have to remind us what we were supposed to do here, as your fork no longer exists.

**Comment by Malabarba** [comment]
No idea. Guess we can close this for now. :-)

**Comment by bbatsov** [comment]
My guess is that `err-info` is discarding the root cause or something like this.

**Comment by cichli** [comment]
Possibly you're referring to the `root-ex` slot that regular nREPL eval returns? https://github.com/clojure/tools.nrepl/blob/master/src/main/clojure/clojure/tools/nrepl/middleware/interruptible_eval.clj#L122-L124

**Comment by bbatsov** [comment]
Ah, yes. I'm pretty sure this is what I meant.

**Comment by bbatsov** [comment]
@sanjayl Maybe you'd like to tackle this task as well?

**Comment by mallt** [comment]
Would it suffice for this issue to simply add a `:root-ex` key to the error summary that holds the classname of the root cause?
