### ISSUE TITLE
resource collision with cljfmt

### ISSUE THREAD

**Issue by bendlas** [clojure-emacs/cider-nrepl#232]
see https://github.com/benedekfazekas/mranderson/issues/8

**Comment by bbatsov** [comment]
There's not much we can do, as we're obviously using `mranderson`. I'm sure @benedekfazekas will handle this.

**Comment by bendlas** [comment]
Sure, just created the ticket here to keep track of when this can be fixed by an update to mranderson

**Comment by benedekfazekas** [comment]
fixed in mranderson. will close this when new mranderson version is released and updated in cider-nrepl

**Comment by expez** [comment]
533840b283e7bc4f24fc1a8d0ec41a75bb258cd0

**Comment by Malabarba** [comment]
@alexander-yakushev do you think this might solve coa's problem with the cider snapshot?

**Comment by alexander-yakushev** [comment]
It might, thanks for heads up.
