### ISSUE TITLE
Java process hangs around after quitting cider on restarting on windows 7

### ISSUE THREAD

**Issue by metatron-the-chronicler** [clojure-emacs/cider-nrepl#234]
When I quit or restart cider inside Emacs there is always one java process that is still running. Two new processes always get started when subsequently restarting the repl.  If I have one java process still running on the first restart I will have three processes, on the second restart I end up with four processes and so on.  Even closing Emacs leaves the process running.

I'm using cider-nrepl 0.10.0-SNAPSHOT, and tools.nrepl 0.2.10.
I have cider version 20150630.1406 and Emacs 24.4.1.

**Comment by bbatsov** [comment]
This is a known Emacs limitation on Windows. There's nothing we can do (or at least I'm out of ideas). See https://github.com/clojure-emacs/cider/issues/390
