### ISSUE TITLE
Help mostly not available in Clojure buffer

### ISSUE THREAD

**Issue by asampal** [clojure-emacs/cider-nrepl#239]
I'm logging this issue here, after having started with company-quickhelp, then company, both of which say that this is not their doing.

I'm seeing strange behavior from company, in Clojure buffers. First I should mention that completion (and the popup with candidates) is happening as expected, both in my `*cider-repl*` buffer and in the Clojure buffer.

The problem has to do with help; in the `*cider-repl*` buffer help is available for all candidates while in the Clojure buffer I can only get help for the prefix 'def'. Just to be clear, all the candidates are there (along with the annotations, but C-h shows 'No documentation available' for any other prefixes.

cider 20150722.216, cider-nrepl 0.10.0-SNAPSHOT, nREPL 0.2.10, clojure 1.7.0 on Windows 8.1 64 bit, Emacs 24.5.1.

**Comment by bbatsov** [comment]
I'm guessing you're referring `company`'s help right?

**Comment by bbatsov** [comment]
Seems to work just fine for me. I'll need some reliable repro steps to debug your issue.

**Comment by asampal** [comment]
Yes, I'm referring to `company` here; quickhelp supposedly asks company for help for the candidate that's currently selected.

Company seems to be working fine, in that the completions popup is shown with all the annotated candidates I'm expecting. company-quickhelp also seems to work since it does show the doc for 'def'. 

What could I do to provide you with more info in order to debug this?

**Comment by Malabarba** [comment]
>  quickhelp supposedly asks company for help ...

Quickhelp is a package that automatically displays a popup with the documentation right?
Earlier you said `C-h` wasn't working, which is a different thing (IIUC). 
Does this mean both the manual method (`C-h`) and the automatic popups are not working?

> What could I do to provide you with more info in order to debug this?

A minimal list of steps to reproduce this starting from an empty project.

Other things you can try:

1. Create a new (clean) project with `lein new`. Does the problem also happen there?
2. What if you uninstall `company-quickhelp`, does `C-h` still not work then?

**Comment by asampal** [comment]
Yes, both quickhelp and C-h don't show documentation. Lars (of quickhelp) mentioned that if C-h doesn't show help as available then neither would he be able to.

This _is_ on a new lein project - there's not much there other than the default foo function that the lein template creates. With `company-quickhelp` uninstalled, C-h still doesn't display help for anything other than 'def', in a Clojure buffer. Again, help works in the `*cider-repl*` buffer.

**Comment by expez** [comment]
Did you figure this out, @asampal?  You might have to load the buffer, using `C-c C-k` to get documentation.

**Comment by asampal** [comment]
Never got it to work for me, Lars. I'll give this a try when I get home
from holidays.  I'm pretty sure I tried this, but maybe not.

**Comment by asampal** [comment]
I guess I never tried the help with the buffer loaded after all; loading the buffer does make the help appear. I think the fact that all the completions appeared made me think that cider-nrepl was already providing the relevant info.
