### ISSUE TITLE
Not possible to disable loading/unloading of namespaces by refresh middleware

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider-nrepl#240]
To reproduce, just write `(defonce hi 1)` in a file, load it, change it to `2`, and then call `cider-refresh`.

I was surprised to find out about this. Is it intended?

I use `defonce` to define an atom which will hold a web server process. This way I can hit `C-c C-k` in the buffer without worry that I'll lose the reference to the process.
Given that `cider-refresh` doesn't kill background processes, it might be best if it didn't reload `defonce`s.

**Comment by cichli** [comment]
`tools.namespace` actually _unloads_ all of your code before reloading it from disk, including things with `defonce` semantics (like `defonce` and `defmulti`) - see [here](https://github.com/clojure/tools.namespace#no-global-state).

It's still fine to keep your web server state in a global atom, but I would recommend creating two functions - one to start the process and `def` the global atom, and another to stop the process. You can then set `cider-refresh-after-fn` and `cider-refresh-before-fn` to the names of these functions (`.dir-locals.el` is useful for this).

If your program requires more than one stateful component, having a `start` fn that `def`s a bunch of global stateful things can become hard to reason about. Check out either of the [component](https://github.com/stuartsierra/component) or [yoyo](https://github.com/jarohen/yoyo) libraries for ways to manage this - the former encapsulates the stateful bits of your programs with records, and the latter with function closures, but both allow you to write programs that are both stateful and reloadable.

**Comment by cichli** [comment]
You can in fact disable reloading of namespaces when using `tools.namespace` by attaching metadata to the namespace:

```clojure
(ns ^{:clojure.tools.namespace.repl/load false
      :clojure.tools.namespace.repl/unload false}
  some.cool.ns
  (:require [clojure.set :refer [rename-keys]]))
```

However since the `tools.namespace` dep in question has been rewritten by `mranderson`, you'd actually have to prefix those namespaced keywords with something like `mranderson045.toolsnamespace.v0v2v10.`, which is far from ideal - we should still provide a way to disable loading/unloading of namespaces by `cider-refresh`. I'll think about how best to do that :-).

**Comment by Malabarba** [comment]
Thanks for the explanation @cichli . Indeed, I think I'll use a `cider-before-refresh-fn` to make sure the server is killed.
Would you like me to close this, or leave it open as a reminder of that last comment?

**Comment by grammati** [comment]
I'm not 100% clear from the discussion above - is this supposed to work now? I am finding that defonce is still reloaded, even with the namespace metadata as described in the comment in refresh.clj. Is there something else I can do to prevent reloading?

**Comment by cichli** [comment]
@grammati I can confirm it works locally - you'll need to depend on `[cider/cider-nrepl "0.10.0-SNAPSHOT"]` though, since we haven't yet released a stable version containing the change.

**Comment by grammati** [comment]
Hi @cichli, I think I have figured out why this never worked for me (namespaces always get refreshed, regardless of metadata).

It looks like even string literals (eg: here https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/refresh.clj#L32) are getting mranderson-ified.

Here is the code as it appears in the cider-nrepl jar:

```clojure
(defn- load-disabled?
  [sym]
  (false? (get (meta (find-ns sym))
               (keyword "cider.inlined-deps.toolsnamespace.v0v2v11.clojure.tools.namespace.repl" "load"))))
```
