### ISSUE TITLE
ns-path only handles clojure code

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider-nrepl#248]
Working in a cljc file, with only a clj repl going, I wanted to check out the generator namespace of test.check so I hit `C-c C-.` to jump to that ns.  The `clojure.test.check.*` namespaces aren't included in the result set from `ns-path`.  I thought maybe this was due to their moving to cljc but they've opted to keep separate clj and cljs files.

If anyone wants to look at this I was working on [superstring](https://github.com/expez/superstring) when this happened.

**Comment by cichli** [comment]
@expez is still this an issue with the latest snapshot? test.check uses cljc now, but I tried with `[org.clojure/test.check "0.8.2"]` (the latest version I could find that doesn't use cljc) and `ns-list` contained its namespaces.

**Comment by expez** [comment]
> @expez is still this an issue with the latest snapshot?

Yes, but the issue is badly named.  The problem is with the `ns-path` op, and not with `ns-list`.  Sorry about that!
