### ISSUE TITLE
Middleware Warnings and Errors when starting Cider repl

### ISSUE THREAD

**Issue by doubleagent** [clojure-emacs/cider-nrepl#254]
Messages:
![image](https://cloud.githubusercontent.com/assets/56522/9918337/d57cd220-5c8b-11e5-95c8-82da8be9dd25.png)

profiles.clj
![image](https://cloud.githubusercontent.com/assets/56522/9918360/f86c96bc-5c8b-11e5-9b4e-cda655915ad9.png)

What should I do?

**Comment by Malabarba** [comment]
Give the warnings a careful read. Your profiles.clj is using old versions of both cider-nrepl and refactor-nrepl. Use the versions requested by the warnings.

**Comment by doubleagent** [comment]
That did the trick.
