### ISSUE TITLE
Upgrade mranderson to support consuming cljc files

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider-nrepl#256]
I think this is why the build is failing on master now.  The huge bump in cljs version the other day brought in a lot of cljc files from that project.  Even though cljs isn't marked as a `:source-dep` this seems to interfere with the build.

**Comment by bbatsov** [comment]
Let's see what @cichli's investigation will uncover first. I actually thought the huge bump wasn't that huge, as even before ClojureScript was essentially 1.7 only, but I guess I was mistaken.

**Comment by bbatsov** [comment]
In the mean time I've reverted the commit .

**Comment by bbatsov** [comment]
@expez I'm guessing this is no longer relevant, right?

**Comment by cichli** [comment]
Yeah, I incidentally bumped the version so we could depend on `fipp` (after debugging the issue myself for an hour so before realising it was already fixed in 0.4.6, whoops) - didn't think to close this issue though, my bad :-).
