### ISSUE TITLE
No method in multimethod error in nRepl session embedding cljs

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/cider-nrepl#260]
This weird error happens while I am connected to ```figwheel```/```ClojureScript``` repl through a nRepl session using the following setup:

```Clojure
:dependencies [[org.clojure/clojure "1.7.0"]
                 [org.clojure/clojurescript "1.7.122"]
                 [reagent "0.5.1"]]

........

:profiles {:dev {:dependencies [[com.cemerick/piggieback "0.2.1"]
                                  [org.clojure/tools.nrepl "0.2.10"]]
                   :repl-options {:nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}
                   :figwheel {:nrepl-port 5088
                              ;; Load CIDER, refactor-nrepl and piggieback middleware
                              :nrepl-middleware ["cider.nrepl/cider-middleware"
                                                 "refactor-nrepl.middleware/wrap-refactor"
                                                 "cemerick.piggieback/wrap-cljs-repl"]}}})

```

```
Exception updating the ns-cache #error {
 :cause No method in multimethod 'ns-as-map' for dispatch value: null
 :via
 [{:type java.lang.IllegalArgumentException
   :message No method in multimethod 'ns-as-map' for dispatch value: null
   :at [clojure.lang.MultiFn getFn MultiFn.java 156]}]
 :trace
 [[clojure.lang.MultiFn getFn MultiFn.java 156]
  [clojure.lang.MultiFn invoke MultiFn.java 229]
  [cider.nrepl.middleware.track_state$calculate_used_aliases$fn__23078 invoke track_state.clj 127]
  [clojure.core.protocols$fn__6523 invoke protocols.clj 167]
  [clojure.core.protocols$fn__6478$G__6473__6487 invoke protocols.clj 19]
  [clojure.core.protocols$seq_reduce invoke protocols.clj 31]
  [clojure.core.protocols$fn__6506 invoke protocols.clj 101]
  [clojure.core.protocols$fn__6452$G__6447__6465 invoke protocols.clj 13]
  [clojure.core$reduce invoke core.clj 6519]
  [cider.nrepl.middleware.track_state$calculate_used_aliases invoke track_state.clj 122]
  [cider.nrepl.middleware.track_state$update_and_send_cache invoke track_state.clj 161]
  [clojure.lang.AFn applyToHelper AFn.java 156]
  [clojure.lang.AFn applyTo AFn.java 144]
  [clojure.core$apply invoke core.clj 632]
  [clojure.core$update_in doInvoke core.clj 5923]
  [clojure.lang.RestFn applyTo RestFn.java 146]
  [clojure.core$apply invoke core.clj 636]
  [clojure.core$binding_conveyor_fn$fn__4444 doInvoke core.clj 1928]
  [clojure.lang.RestFn applyTo RestFn.java 146]
  [clojure.lang.Agent$Action doRun Agent.java 114]
  [clojure.lang.Agent$Action run Agent.java 163]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 617]
  [java.lang.Thread run Thread.java 745]]}
```

I skimmed the code and it looks ```ns-as-map``` is passed a ```nil``` but I don't see where it comes from.

**Comment by lvh** [comment]
Yep; I'm getting the same error since updating to the most recent version of cider.

**Comment by arichiardi** [comment]
It looks like it happens in the ```cljs.user``` namespace only, but I am not very sure about it.

**Comment by lvh** [comment]
I'm seeing this in other namespaces too:

```
bubbles.xml> Exception updating the ns-cache #error {
 :cause No method in multimethod 'ns-as-map' for dispatch value: null
 :via
 [{:type java.lang.IllegalArgumentException
   :message No method in multimethod 'ns-as-map' for dispatch value: null
   :at [clojure.lang.MultiFn getFn MultiFn.java 156]}]
 :trace
 [[clojure.lang.MultiFn getFn MultiFn.java 156]
  [clojure.lang.MultiFn invoke MultiFn.java 229]
  [cider.nrepl.middleware.track_state$calculate_used_aliases$fn__26152 invoke track_state.clj 127]
  [clojure.core.protocols$fn__6523 invoke protocols.clj 167]
  [clojure.core.protocols$fn__6478$G__6473__6487 invoke protocols.clj 19]
  [clojure.core.protocols$seq_reduce invoke protocols.clj 31]
  [clojure.core.protocols$fn__6506 invoke protocols.clj 101]
  [clojure.core.protocols$fn__6452$G__6447__6465 invoke protocols.clj 13]
  [clojure.core$reduce invoke core.clj 6519]
  [cider.nrepl.middleware.track_state$calculate_used_aliases invoke track_state.clj 122]
  [cider.nrepl.middleware.track_state$update_and_send_cache invoke track_state.clj 161]
  [clojure.lang.AFn applyToHelper AFn.java 156]
  [clojure.lang.AFn applyTo AFn.java 144]
  [clojure.core$apply invoke core.clj 632]
  [clojure.core$update_in doInvoke core.clj 5923]
  [clojure.lang.RestFn applyTo RestFn.java 146]
  [clojure.core$apply invoke core.clj 636]
  [clojure.core$binding_conveyor_fn$fn__4444 doInvoke core.clj 1928]
  [clojure.lang.RestFn applyTo RestFn.java 146]
  [clojure.lang.Agent$Action doRun Agent.java 114]
  [clojure.lang.Agent$Action run Agent.java 163]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 617]
  [java.lang.Thread run Thread.java 745]]}
```

What version of CIDER are you running?

**Comment by arichiardi** [comment]
```Clojure
[cider/cider-nrepl "0.10.0-SNAPSHOT"]
[org.clojure/tools.nrepl "0.2.10"]
```

**Comment by lvh** [comment]
That's the Clojure side of things; which version of cider (the emacs package)?

**Comment by arichiardi** [comment]
Oh, well also ```cider``` inside emacs is latest snapshot ```0.10.0-SNAPSHOT```

**Comment by lvh** [comment]
Did you get it from MELPA?

**Comment by arichiardi** [comment]
I am leaving on the edge and I might have to pull ```HEAD```, let me try.

**Comment by lvh** [comment]
It's definitely CIDER; downgrading to 0.9.1 resolved the issue.

**Comment by Malabarba** [comment]
> I skimmed the code and it looks ns-as-map is passed a nil but I don't see where it comes from.

Yes, and from the stack trace it seems to be happening inside calculate_used_aliases.

**Comment by Malabarba** [comment]
It's almost certainly happening on this line: https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/track_state.clj#L127

This indicates there's a namespace that's being require but that can't be resolved (thus the nil value). 
It's easy to patch but I would like to understand why it's happening. Anyone have a clue?

**Comment by arichiardi** [comment]
Yes that's it, ```(find-ns name)``` fails. Maybe the namespace is not loaded in the ```cljs``` repl?
I mean, we are in a nRepl session which embeds (through ```piggieback``` I guess) a ```cljs``` repl.
Maybe the namespace is loaded in nRepl but not in the ```cljs``` repl?
I am not aware of all the interactions between the two...it is more like a feeling I have. I am available for testing anything you want me too though.

**Comment by lvh** [comment]
I'm guessing it's the distinction between `cljs.user` and `user`.

**Comment by arichiardi** [comment]
Yeah it smells like it, but sometimes the error appears in custom nss...

**Comment by Malabarba** [comment]
You're right, I see it now. I messed up. 
That line is supposed to use `cljs-ana/find-ns` instead of `find-ns` (which obviously can only find clojure namespaces).

**Comment by arichiardi** [comment]
I am glad you found it!!

**Comment by Malabarba** [comment]
Should be fixed now, I'll push the snapshot when I get home.

**Comment by lvh** [comment]
Awesome, thanks @Malabarba !

**Comment by arichiardi** [comment]
thanks @Malabarba!  I am looking forward to having the snap then :smile:

**Comment by Malabarba** [comment]
It's up now. Let me know if it works.

**Comment by bilus** [comment]
I'm on 0.10.0-SNAPSHOT and I'm still getting this error.

**Comment by Malabarba** [comment]
Could you paste here the entire exception you get?

**Comment by bilus** [comment]
Sure, here are the full REPL contents:

```
; CIDER 0.10.0snapshot (package: 20150925.725) (Java 1.8.0_05, Clojure 1.7.0, nREPL 0.2.11)
user> To quit, type: :cljs/quit
nil
cljs.user> 
cljs.user> (require 'reforms.core)
nil
cljs.user> Exception updating the ns-cache #error {
 :cause No method in multimethod 'ns-as-map' for dispatch value: null
 :via
 [{:type java.lang.IllegalArgumentException
   :message No method in multimethod 'ns-as-map' for dispatch value: null
   :at [clojure.lang.MultiFn getFn MultiFn.java 156]}]
 :trace
 [[clojure.lang.MultiFn getFn MultiFn.java 156]
  [clojure.lang.MultiFn invoke MultiFn.java 229]
  [cider.nrepl.middleware.track_state$update_and_send_cache$fn__20682 invoke track_state.clj 166]
  [clojure.core$map$fn__4553 invoke core.clj 2622]
  [clojure.lang.LazySeq sval LazySeq.java 40]
  [clojure.lang.LazySeq seq LazySeq.java 49]
  [clojure.lang.RT seq RT.java 507]
  [clojure.core$seq__4128 invoke core.clj 137]
  [clojure.core.protocols$seq_reduce invoke protocols.clj 30]
  [clojure.core.protocols$fn__6506 invoke protocols.clj 101]
  [clojure.core.protocols$fn__6452$G__6447__6465 invoke protocols.clj 13]
  [clojure.core$reduce invoke core.clj 6519]
  [clojure.core$into invoke core.clj 6600]
  [cider.nrepl.middleware.track_state$update_and_send_cache invoke track_state.clj 167]
  [clojure.lang.AFn applyToHelper AFn.java 156]
  [clojure.lang.AFn applyTo AFn.java 144]
  [clojure.core$apply invoke core.clj 632]
  [clojure.core$update_in doInvoke core.clj 5923]
  [clojure.lang.RestFn applyTo RestFn.java 146]
  [clojure.core$apply invoke core.clj 636]
  [clojure.core$binding_conveyor_fn$fn__4444 doInvoke core.clj 1928]
  [clojure.lang.RestFn applyTo RestFn.java 146]
  [clojure.lang.Agent$Action doRun Agent.java 114]
  [clojure.lang.Agent$Action run Agent.java 163]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 617]
  [java.lang.Thread run Thread.java 745]]}
```

**Comment by bilus** [comment]
Just in case, here's `project.clj`:

```clojure
(defproject reforms "0.4.0-SNAPSHOT"
            :description "Form helpers for React-based Clojurescript libraries."
            :url "http://bilus.github.io/reforms/"
            :license {:name "Eclipse Public License"
                      :url  "http://www.eclipse.org/legal/epl-v10.html"}
            :dependencies [[org.clojure/clojure "1.7.0"]
                           [org.clojure/clojurescript "1.7.122"]]
            :jar-exclusions [#"\.cljx|\.swp|\.swo|\.DS_Store"]
            :auto-clean false
            :source-paths ["src"]

            :plugins [[lein-cljsbuild "1.1.0"]
                      [lein-doo "0.1.4"]]

            :clean-targets ^{:protect false} ["target/"
                                              "resources/public/js/testable.js"]

            :codox {:language                  :clojurescript
                    :include                   [reforms.core reforms.core.options reforms.validation]
                    :src-dir-uri               "http://github.com/bilus/reform/blob/master/"
                    :src-linenum-anchor-prefix "L"
                    :defaults                  {:doc/format :markdown}}

            :profiles {:doc {:dependencies [[org.clojure/clojurescript "0.0-2985"]]}
                       :dev {:dependencies [[org.clojure/core.async "0.1.346.0-17112a-alpha"]
                                            [com.cemerick/piggieback "0.2.1"]
                                            [cider/cider-nrepl "0.10.0-SNAPSHOT"]]
                             :repl-options {:nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}}}

            :aliases {"doc"       ["with-profile" "doc" "doc"]
                      "cljsbuild" ["with-profile" "dev" "cljsbuild"]}

            :cljsbuild {:builds {:test {:source-paths ["src" "test"]
                                        :compiler     {:output-to     "resources/public/js/testable.js"
                                                       :main          'reforms.runner
                                                       :optimizations :whitespace}}}})

```

**Comment by bilus** [comment]
I pushed the 0.4.0 branch in case it makes it easier to recreate the problem:

https://github.com/bilus/reforms/tree/0.4.0

**Comment by Malabarba** [comment]
In all the decades that Java's been around,  has nobody bothered to make stack traces display arglists? 😥

**Comment by bilus** [comment]
*lol* I forked the project to modify it so it logs the arguments, pushed it to clojars and lo and behold -- it works without a glitch. Does clojars have you latest fixes?

**Comment by Malabarba** [comment]
Hm. Let me check. Maybe I just messed up...

**Comment by bilus** [comment]
After 'downgrading' to the official version the errors does show up again.

**Comment by Malabarba** [comment]
That's strange. I just started up a project and the fix is deifinitely there.

If you `cider-jack-in`, then write `cider.nrepl.middleware.track-state` in a clojure buffer, and then call `cider-find-var` on it, what do you see on line 162?
You should see the following:

        find-ns-fn (if cljs
                     #(cljs-ana/find-ns cljs %)
                     find-ns)

**Comment by bilus** [comment]
I've done it previously to make sure I have the correct version and the code was there (and still is). And yet, the error has been showing up and still is unless I switch to the forked version.

I just recreated it using 'your' version. Then switched to 'mine' and after `cider-jack-in-clojurescript` the error no longer shows up.

I'll do a diff in a sec.

**Comment by bilus** [comment]
There are differences similar to the one below:

![screen shot 2015-09-28 at 13 49 42](https://cloud.githubusercontent.com/assets/1025537/10134676/e9245fa4-65e7-11e5-9c80-eb7b3f0ce6e0.png)

(?)

**Comment by Malabarba** [comment]
Yeah, that diff is fine. The namespaces are renamed by mranderson when we build the snapshot, but it won't affect a version you installed locally.
I guess this could be mranderson bug, @benedekfazekas?

**Comment by bilus** [comment]
@malabarba Are you able to recreate the error using the reforms project?

**Comment by Malabarba** [comment]
Haven't had a chance to try it yet. Will try as soon as I can.

**Comment by Malabarba** [comment]
Ok. I've spotted the issue.

**Comment by bilus** [comment]
I'm so glad to hear that. It's pretty erratic. I just started Emacs -- the problem wasn't there; restarted it -- the error shows up. Did the latter twice to make sure there's no special action sequence involved.

**Comment by Malabarba** [comment]
In one of your files, you import `IdGenerator` from the `goog.ui` namespace.
The reason this caused the exception is that `cljs-tooling.cljs-tooling.util.analysis/all-ns` reports this `:import` to us as if it were a `:require [goog.ui.IdGenerator :as IdGenerator]`.
This causes us to treat it as an alias, and when we try to find the `goog.ui.IdGenerator` namespace it returns nil.

I don't know if this is a bug or if I was just using it wrong. @cichli @gtrak, Maybe one of you can tell? Is it correct that imports are listed in the `:requires` entry of the namespace map? (as returned by `all-ns`)

OTOH, @bilus, the fact that it didn't happen when you forked the repo intrigues me a little.

**Comment by bilus** [comment]
I did more testing and it turns out that forking the repo had nothing to with it. It just sporadically worked correctly even with the original repo (same project). 

At some point I thought updating CIDER itself solved the issue because the error was gone after restarting Emacs but - after another restart - it shows up again. Sorry for a false lead.

**Comment by bilus** [comment]
This may or may not be related but here's what just transpired (official cider-nrepl):

```
cljs.user> (require 'reforms.core)
nil
cljs.user> (require 'reforms.impl)
clojure.lang.ExceptionInfo: No such namespace: reforms.impl, could not locate reforms/impl.cljs, reforms/impl.cljc, or Closure namespace "reforms.impl" {:tag :cljs/analysis-error}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at cljs.analyzer$error.invoke(analyzer.cljc:543)
	at cljs.analyzer$error.invoke(analyzer.cljc:541)
	at cljs.analyzer$analyze_deps.invoke(analyzer.cljc:1649)
	at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:2485)
	at cljs.analyzer$analyze_STAR_$fn__3209.invoke(analyzer.cljc:2566)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:333)
	at clojure.core$reduce.invoke(core.clj:6518)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:2566)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2581)
	at cljs.repl$evaluate_form.invoke(repl.cljc:439)
	at cljs.repl$fn__5564$self__5576.invoke(repl.cljc:652)
	at cljs.repl$repl_STAR_$read_eval_print__5630.invoke(repl.cljc:833)
	at cljs.repl$repl_STAR_$fn__5636$fn__5645.invoke(repl.cljc:874)
	at cljs.repl$repl_STAR_$fn__5636.invoke(repl.cljc:873)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1143)
	at cljs.repl$repl_STAR_.invoke(repl.cljc:837)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at cemerick.piggieback$run_cljs_repl$fn__6081.doInvoke(piggieback.clj:159)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at cemerick.piggieback$run_cljs_repl.invoke(piggieback.clj:169)
	at clojure.lang.AFn.applyToHelper(AFn.java:171)
	at clojure.lang.AFn.applyTo(AFn.java:144)
```

Notice that the namespace does load in the above instance. Then I try to require a non-existent namespace, then one that does exist but the error incorrectly refers to the non-existent one.

The reason it may be related is a fact about the #260 issue I neglected to mention which is that after the original error, one cannot use the REPL in that even pressing ENTER with no expression before the cursor triggers the same error.

**Comment by acron0** [comment]
I'm still having this issue too. Details are here: https://github.com/bhauman/lein-figwheel/issues/245#issuecomment-143988850

**Comment by Malabarba** [comment]
I'll push a proper fix once I get some feedback about cljs-tooling.
But, for anyone who just wants to get some work done, evaluating this in the REPL should be a workaround 

    (in-ns 'cider.nrepl.middleware.track-state)
    (defmethod ns-as-map nil [_] {})

**Comment by bilus** [comment]
Thanks! Will give it a try.

**Comment by bilus** [comment]
Seems to do the trick. I'll keep you posted if anything comes up.
