### ISSUE TITLE
Complaining about version while version seems ok

### ISSUE THREAD

**Issue by skrat** [clojure-emacs/cider-nrepl#272]
This is my `~/.lein/profiles.clj`
```
{:user
 {:plugins
  [[cider/cider-nrepl "0.10.0-SNAPSHOT"]
   [com.cemerick/piggieback "0.2.1"]
   [refactor-nrepl "1.1.0-SNAPSHOT"]
   [lein-try "0.4.3"]]
  :repl-options {:nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}
  :dependencies [[org.clojure/tools.nrepl "0.2.10"]]}}
```

and this is what I get in the REPL: https://www.refheap.com/111840

The REPL is not fully functional then, no completion to name one.

**Comment by expez** [comment]
What happens when you do `M-x clj-refactor-version <RET>`? I basically want to know if that plugin worked and if this is only about cider-nrepl.

Here's a few other problems you should address while you're at it:

* Update tools.nrepl to 0.2.12
* Move piggieback from plugins to dependencies.

**Comment by skrat** [comment]
It says `nrepl-refactor middleware not available! ...` I did the other things to `profiles.clj` but it didn't fix the problem.

**Comment by expez** [comment]
What happens when you do 

`$ lein try clj-time "0.5.1"`?

I'm guessing that isn't going to work either.  It's starting to look like `lein` is ignoring your `profiles.clj` entirely.

To test this hypothesis you could create a new project with `lein new test` and then, under `:dependencies` in `project.clj`, add `:plugins [[lein-pprint "1.1.0"]]` and finally, with a shell in that project directory, run `lein pprint` and paste the output here.

Also, what OS are you on?

**Comment by skrat** [comment]
@expez Thanks for looking into this. `lein try` works, and I don't think the `profiles.clj` is ignored, because when I adjusted it (updating `tools.nrepl`), it worked, when I've run it, it downloaded that new version of `tools.nrepl`.

I should probably mention that the nREPL is sprung by `lein-figwheel`. Any idea how to debug this issue? Would installing/using `cider-spy` package help?

**Comment by skrat** [comment]
I'm on Linux, and the output of `lein pprint` is https://gist.github.com/skrat/13170ecceec3a767405a

**Comment by expez** [comment]
> I should probably mention that the nREPL is sprung by `lein-figwheel`

Aha!  You gotta do [this](https://github.com/bhauman/lein-figwheel/blob/master/doc/editor_repls.md#nrepl-middleware-cider-etc)

**Comment by skrat** [comment]
@expez ur golden, I gotta stamp this on my forehead. Thank you
