### ISSUE TITLE
Check for Clojure and Leiningen version compatibility in the plugin

### ISSUE THREAD

**Issue by cichli** [clojure-emacs/cider-nrepl#277]
If Clojure < 1.7 or Lein < 2.5.2, log a warning and don't add the dependency or middleware to the project.

**Comment by bbatsov** [comment]
Yeah, that'd be great. We should probably add the lein info to the session description or something, as we'll still need a way to pass it to the UI.

**Comment by bbatsov** [comment]
And given the number of issue reports we're getting lately - solving this should be one of our top priorities...

**Comment by cichli** [comment]
Well, if they're using Lein < 2.5.2, the process will fail to even start - but there's no harm in informing the client of the version, so I'll include it there too :-).

**Comment by bbatsov** [comment]
Excellent. :-)

**Comment by Malabarba** [comment]
Is there a way to get the lein version without manually running `lein version`? And, if not, would that take several seconds?

**Comment by cichli** [comment]
> Is there a way to get the lein version without manually running lein version? And, if not, would that take several seconds?

In the plugin we can just call `leiningen.core/leiningen-version`. In the process where the middleware is actually loaded, it's painful (shelling out like you say) or potentially impossible (if `lein` is not on `$PATH`, we don't know where to look).

So thinking about it some more, I don't think informing the client of the lein version makes much sense. Not everyone using `cider-nrepl` does so via the plugin - e.g. boot users, or people who embed nREPL in their applications in other ways. The emacs client can always run `lein version` in the background as a sanity check I guess, but even then there would be false positives (people who have an old version but don't use it anymore because they use boot now, for example).

**Comment by bbatsov** [comment]
Well, I'm fine with anything that won't leave the users guessing what exactly went wrong.
