### ISSUE TITLE
Do we now need to add Clojure 1.7.0 as a dependency in profiles.clj?

### ISSUE THREAD

**Issue by sanjayl** [clojure-emacs/cider-nrepl#279]
Hi, the latest snapshot (20151221) started spitting out warnings when I used Lein outside of an existing project (for example, when doing a "lein new" or a "lein repl" as a scratchpad). The warnings are:

"Warning: cider-nrepl requires Clojure 1.7 or greater.
Warning: cider-nrepl will not be included in your project."

It looks like the dependency map passed to the new cider-nrepl.plugin/middleware function doesn't contain org.clojure/clojure since this use case doesn't have a project.clj to declare it as a dependency. 

Adding an explicit Clojure dependency to my profiles.clj makes the warning go away, but I wasn't sure if that's the right thing to do?

Thanks!

**Comment by cichli** [comment]
Thanks for the report; this was an edge case I definitely tested at some point while developing the feature but evidently then changed some code afterwards and didn't test again :-).

If you're using a supported version of Leiningen and don't have any Clojure dep specified (e.g. transitively by some other dependency/plugin), it'll use 1.7 by default anyway, so you shouldn't need to add it to your profiles.clj.

**Comment by Malabarba** [comment]
Yes. It is the correct thing to do. 👍

**Comment by sanjayl** [comment]
Thanks for the fix!
