### ISSUE TITLE
Info middleware errors when getting eldoc for "." special operator

### ISSUE THREAD

**Issue by sanjayl** [clojure-emacs/cider-nrepl#293]
I get an ugly stack trace when I type the dot operator special form and trigger an eldoc query.
Here's the code to reproduce:
```clojure
(ns cider.nrepl.middleware.eldoc-bug
  (:require [cider.nrepl.test-session :as session]))

(session/session-fixture #(session/message {:op "eldoc" :ns "user" :symbol "."}))
```
Or you can just open the cider-repl, type `(.` and then wait long enough to trigger a query.

The Exception gets thrown in the `extract-eldoc` function of `cider.nrepl.middleware.info` [lines 265-7.](https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/info.clj#L265-L267) 
```clojure
(cond
  (:special-form info) (->> (:forms info)
                            (map vec))
```
The call to `(:forms info)` for the dot operator returns:
```clojure
[( .instanceMember instance args* )
 ( .instanceMember Classname args* )
 ( Classname/staticMethod args* )
 Classname/staticField ]
```
The last item of this collection causes `vec` to blow up since it's a symbol and not a coll.

I guess it can be fixed by having the mapping function branch on type, but I thought it looked weird:
```
(->> (:forms info)
     (map #(if (coll? %) (vec %) (vector %))
```
Is there a more idiomatic way of doing this?

**Comment by bbatsov** [comment]
Thanks for spotting this. Nothing better comes to mind, so I guess I'll fix this using a similar solution.
