### ISSUE TITLE
Cyclic dependency error is swallowed by cider-refresh

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider-nrepl#302]
When using cider-refresh it will tell you that there's a cyclic dependency between namespaces A and B, but it omits the details about how that cycle came about.  I had to do `lein repl` to discover namespaces C and D which linked A and B together in a cycle.

**Comment by bbatsov** [comment]
I won't be able to look into this soon, but I hope @cichli will have some time.

**Comment by sanjayl** [comment]
The error isn't actually swallowed, rather, the members of the cyclic graph are never provided to CIDER in the first place. The cycle is detected inside [`clojure.tools.namespace.dependency`](https://github.com/clojure/tools.namespace/blob/master/src/main/clojure/clojure/tools/namespace/dependency.cljc#L87-L93), but that code does not provide any path information on how the cycle was formed.

This is in contrast to [the code used by `clojure.core/load`](https://github.com/clojure/clojure/blob/master/src/clj/clojure/core.clj#L5781-L5792) which will explicitly tell you the path taken to reach the cyclic dependency.

I don't know any graph theory, and I don't particularly understand what's going on in `clojure.core/load`, so I don't know how to replicate the breadcrumbs in the clojure.core code at this point.

The dependency graph is represented by a map, with the keys being namespaces and the values being a set of namespaces required by the key, so if any of you have any ideas on how to replicate the functionality of `clojure.core/load` using this data structure, then it shouldn't be too hard to get that information into the exception. 

If you want to play around the dependency map data structure that CIDER'll have access to at the time of the exception, you can do something like this:
```clojure
;; Make sure you have [org.clojure/tools.namespace "0.2.11"] in your dependency vector
(require '[clojure.tools.namespace.dir :as dir])
(require '[clojure.tools.namespace.dependency :as dep])

(:depmap (#'file/files-and-deps (#'dir/modified-files {} (#'dir/find-files (#'dir/dirs-on-classpath)))))

;; or if you prefer a threaded version of the above:
(->> (#'dir/dirs-on-classpath)
     (#'dir/find-files)
     (#'dir/modified-files {})
     (#'file/files-and-deps)
     :depmap)

;; In my simple bug-replication project with a cyclic dependency, I get:
{cyclic-test.core #{cyclic-test.ns-a clojure.string},
 cyclic-test.ns-a #{cyclic-test.ns-b clojure.string},
 cyclic-test.ns-b #{cyclic-test.core clojure.string},
 cyclic-test.core-test #{cyclic-test.core clojure.test}}
```

**Comment by bbatsov** [comment]
@sanjayl It'd be nice if we added some functionality to print the dependency tree in CIDER. What would help debugging a lot of issues and would be super helpful.

**Comment by sanjayl** [comment]
@bbatsov , working on the dependency viewer now

**Comment by bbatsov** [comment]
Great!

On Tuesday, 12 April 2016, sanjayl <notifications@github.com> wrote:

> @bbatsov <https://github.com/bbatsov> , working on the dependency viewer
> now
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider-nrepl/issues/302#issuecomment-209150712>
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by bbatsov** [comment]
Btw, this might be useful for the UI https://github.com/fourier/ztree. I've been thinking of adopting it (or something like it) for the ns browser & classpath browser, but I haven't had much time to play with it yet.

**Comment by sanjayl** [comment]
Here's a [short screencast of the v1 dependency viewer & circular dependency detector](https://youtu.be/FK1SXXp1HP4).

There's still a good amount of fit and finish to be done, so any suggestions are welcome at this stage. The first thing I wanted to add for v2 is the ability to filter out "background noise" namespaces. Also want to change the way the circular dependency info is displayed to differentiate it from the regular dep browser.

I think something like ztree would be very useful for this browser. Will look into using it during the next iterations. At some point, we should probably go through the different UI elements and make sure they're unified in layout, colors, keybindings, etc. Would also like to use something like `magit-popup` to display keybindings, options, etc.

**Comment by bbatsov** [comment]
Good start!

A few remarks:

> The first thing I wanted to add for v2 is the ability to filter out "background noise" namespaces.

This is something we need to tackle in general. Pretty much everywhere where we're dealing with namespaces we should filter out cider's own namespaces (I'm guessing they are what you refer to as "background noise").

I'm also not sure how to name the feature exactly as some people might think it's about dependencies as in "library deps". Btw, it might be useful to show such information about our projects as well (something like `lein deps :tree`).

**Comment by bbatsov** [comment]
> I think something like ztree would be very useful for this browser. Will look into using it during the next iterations. At some point, we should probably go through the different UI elements and make sure they're unified in layout, colors, keybindings, etc.

True. Our UI is definitely a bit inconsistent.

> Would also like to use something like magit-popup to display keybindings, options, etc.

Or we can bundle some hydras https://github.com/abo-abo/hydra

**Comment by sanjayl** [comment]
> Pretty much everywhere where we're dealing with namespaces we should filter out cider's own namespaces (I'm guessing they are what you refer to as "background noise").

 I was thinking more about arbitrary filtering (tooling, standard clojure classes, subsystems that you're not focusing on, etc) since ignoring the `cider` namespaces already works in this browser; I think those namespaces (along with everything in your `.m2` repo) all live outside the default classloader so they aren't displayed. However, when you're working on the `cider-nrepl` codebase, these ns get loaded into the default classloader and `cider`'s dependency information is displayed in this browser.

> I'm also not sure how to name the feature exactly as some people might think it's about dependencies as in "library deps". Btw, it might be useful to show such information about our projects as well (something like lein deps :tree).

That's a really good point. I'm not sure exactly what to call it either now...maybe break it down into `namespace-dependencies` vs `project-dependencies` / `library-dependencies`? Will think about this more.

Hydras sound like a good idea, will give it a try

**Comment by MalloZup** [comment]
autogenerated with https://github.com/MalloZup/doghub:  issue inactive since 450 days. Please update the issue or close it

**Comment by vemv** [comment]
> The error isn't actually swallowed, rather, the members of the cyclic graph are never provided to CIDER in the first place.

This is the tldr of the issue and it's also tracked in tools.namespace's issue tracker.

I'd hope they eventually enrich the exception, other than that it's been too long since this issue was opened
