### ISSUE TITLE
Cider-refresh doesn't refresh namespaces not on the load-path

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider-nrepl#310]
I'm not sure if this is even fixable, but it's something I've run into multiple times.
This comes up for me with test files. Sometimes the `/test` directory is not on the load-path when I start the REPL, but that doesn't keep me from visiting test files and working on them as usual with cider.

The only thing that fails then is cider-refresh. It won't necessarily throw errors, but it also won't refresh the test namespaces.

**Comment by expez** [comment]
Why isn't the `test` directory on classpath?  That seems like a way easier problem to fix :p

**Comment by Malabarba** [comment]
For some reason most projects simply don't add the test dirs to the load-path of the `:dev` profile. `cider-nrepl` itself doesn't.

I could add it manually for my projects, but I think this is something pretty much everybody will run into (they just probably don't realise it :-).

**Comment by expez** [comment]
> For some reason most projects simply don't add the test dirs to the load-path of the :dev profile. 

This is because leiningen already does that.

> cider-nrepl itself doesn't.

`cider-nrepl` actually overrides the default away from `test`.

**Comment by Malabarba** [comment]
Does that mean that the test files *should* be on my load-path when I start the repl?

**Comment by expez** [comment]
> Does that mean that the test files should be on my load-path when I start the repl?

Yes, unless you're overriding [test-paths](https://github.com/technomancy/leiningen/blob/master/sample.project.clj#L281) (or you're still messing around with boot, which I know nothing about)

**Comment by Malabarba** [comment]
You're right. I guess we can close this then. :+1:
