### ISSUE TITLE
Functions in other packages not decorated when tracing

### ISSUE THREAD

**Issue by hanshuebner** [clojure-emacs/cider-nrepl#319]
## Expected behavior

When tracing a function, all occurrences of the symbol naming the traced functions should be decorated with a small blue border.

## Actual behavior

With functions in other packages (i.e. ones that are referenced by a qualified symbol), no blue border appears around the function name.  Also, it seems that decoration is not applied to functions living in .jar files.

## Steps to reproduce the problem

In a clojure file, place cursor on a qualified symbol that refers to a function in another package and type `C-c M-t v RET`.  No blue border will be displayed around the symbol.

### cider-nrepl version

0.11.0

### Java version

1.8

### Operating system

OS X El Capitan

**Comment by Malabarba** [comment]
Are you sure it's all other packages? And not just clojure.core?

**Comment by hanshuebner** [comment]
Yes, it happens for all packages.

**Comment by bbatsov** [comment]
Can someone reproduce this?

**Comment by hanshuebner** [comment]
One other observation is that when I have traced a few non-local functions and they have not been decorated, and then trace a local function, both that local function and the other non-local functions receive their decoration.

**Comment by grammati** [comment]
My observations:
 - the "traced" face seems to only be applied after evaluating something else (eg: switch to the repl and just hit RET)
 - even with the above, the face is only applied (added or removed) if a function in the file's namespace has been traced or untraced
 - the face is never applied to vars loaded from a jar, I think

So, for example, in file foo/bar.clj, we have local function `aaa`, function `bbb/blah` required from another namespace in the same project, and function `xxx/foo` required from a jar:
 - trace function `xxx/foo`
   - nothing highlighted
   - go to REPL, hit enter, still nothing highlighted
 - trace function `bbb/blah`
  - nothing highlighted
  - go to REPL, hit enter, still nothing highlighted
 - trace function `aaa`
  - nothing highlighted
  - to to REPL, hit enter
  - `aaa` and `bbb/blah` become highlighted, but `xxx/foo` does not
