### ISSUE TITLE
Fix the ClojureScript build under OracleJDK 7

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider-nrepl#324]
Someone should investigate what's wrong there. This is the commit which marked those failures as acceptable for the time being https://github.com/clojure-emacs/cider-nrepl/commit/86f6685a6ff94ae6f1664fbd22cb90965391f667

**Comment by gonewest818** [comment]
Do you still want to support `openjdk7`?  or drop it and add `openjdk9`?

**Comment by bbatsov** [comment]
We have to support JDK 7, as a lot of people are still using it. And I guess we should add JDK 9 to the build matrix as well. Not sure if we need to have several OpenJDK/OracleJDK versions, though. I don't even remember the exact differences between them these days. I think that in general the matrix for the project is a mess and should be reorganized/simplified (that's also tied to the lein profiles currently in use).

**Comment by bbatsov** [comment]
We should also have `lein test` run some reasonable profile, as many newcomers are surprised it doesn't run almost any tests.

**Comment by gonewest818** [comment]
👌

**Comment by xiongtx** [comment]
This is resolved by #475.
