### ISSUE TITLE
Error in cider-refresh-after-fn killed repl

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider-nrepl#326]
When the function in `cider-refresh-after-fn` threw an exception the repl subprocess was killed.

**Comment by sanjayl** [comment]
@expez, I tried to recreate this bug but was unsuccessful -- although I suspect my test case was oversimplistic. [Here's a screencast of what I tried to do](https://youtu.be/U4LGuUfUCec). Any thoughts on how to reproduce the error?

**Comment by expez** [comment]
@sanjayl This is how I would've tried to reproduce it too.  Is it possible that the new error handling for sync ops fixed this issue too?

**Comment by sanjayl** [comment]
@expez , no, the refresh middleware doesn't use the new error handling for sync ops infrastructure yet. Not sure what could cause a REPL shutdown...Perhaps an example of the `cider-refresh-after-fn` that you are using might help? What kind of exception gets thrown (checked vs unchecked etc)?

**Comment by expez** [comment]
The `after-fn` starts a pretty large system.  IIRC this happened due to a NPE when rewriting the `start` function of some component.

**Comment by bbatsov** [comment]
Guess we can close this if you haven't seen the problem recently.
