### ISSUE TITLE
Debugger fails on static method call

### ISSUE THREAD

**Issue by grammati** [clojure-emacs/cider-nrepl#337]
Although rarely used, static methods can be called like this: `(. clojure.lang.Numbers (inc x))`

The clojure compiler determines statically whether the symbol after the `.` refers to a class. See: https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/Compiler.java#L961

When debugging, we wrap the symbol `clojure.lang.Numbers` in a breakpoint, so the compiler no longer sees it statically as a class, but as an expression, and so the call fails as runtime with "No matching method found: inc for class java.lang.Class".

Note: it looks like the method clojure.lang.Compiler$HostExpr/maybeClass could tell us whether the symbol refers to a class, but it's not accessible. :(

**Comment by grammati** [comment]
Actually, it seems that just checking in the instrumenter using `(instance? Class (resolve sym))` does the trick. I'll send a PR.

**Comment by Malabarba** [comment]
Don't worry about a PR, I'm fixing it now.
I prefer to handle it directly in the `'#{.}` clause of `instrument-special-form`. :+1:

**Comment by grammati** [comment]
Great, thanks! BTW, I found this by stepping in to `inc` :)

**Comment by Malabarba** [comment]
:smile:
