### ISSUE TITLE
Apparent type error in track-state/update-and-send-cache

### ISSUE THREAD

**Issue by arrdem** [clojure-emacs/cider-nrepl#338]
![2016-04-13-141010_563x340_scrot](https://cloud.githubusercontent.com/assets/704767/14506098/c630e77a-0181-11e6-85ab-82d593b0c4dd.png)

stacktrace

![2016-04-13-141057_772x459_scrot](https://cloud.githubusercontent.com/assets/704767/14506101/cb71f3b4-0181-11e6-91cf-10ba38509d28.png)

This got exposed in [Jaunt](https://github.com/jaunt-lang/jaunt), where `RT.get` on non-associative types throws an exception instead of returning nil. Looks like the `new-ns-map` isn't correctly formed, wherever it's coming from.

**Comment by Malabarba** [comment]
I've deployed a fix. Let me know if it works for Jaunt.

**Comment by arrdem** [comment]
Nice. Thanks Artur, I had the feeling I was fixing this in the wrong place.

**Comment by arrdem** [comment]
Working great. Thanks!
