### ISSUE TITLE
Unify test names

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider-nrepl#351]
[This discussion](https://github.com/bbatsov/clojure-style-guide/issues/131#issuecomment-217664452) about test naming conventions made me realize our tests don't have uniform names. We should address this and used `something-test` everywhere consistently. Probably we can even add a bit of code to clojure-mode to enforce consistent test naming (e.g. we can font lock specially test names that don't fit the current configuration or something like this).

**Comment by dpsutton** [comment]
[dan@localhost cider-nrepl]$ grep -r "(deftest" ./ | wc -l
      186

"valid: 49, pluralized: 2, prefixed: 43, missing-suffix: 6, unrecognized: 86"

Building an automatic tool to analyze and fix it.

**Comment by dpsutton** [comment]
https://github.com/clojure-emacs/cider-nrepl/pull/366
