### ISSUE TITLE
Fails to resolve 'resources/see-also.edn' when compiling 'info.clj'

### ISSUE THREAD

**Issue by metamorph** [clojure-emacs/cider-nrepl#354]
I get an error when running `cider-jack-in` from a bare-bones Leiningen project (`lein new test-app`). The cause of the error seems to be that the `see-also.edn` file in `cider-nrepl 0.13.0-SNAPSHOT` is in the root of the JAR-file, not in the `resources` path (I've looked in the JAR-file that was downloaded by leiningen).

 I'm using the default setting for Spacemacs `(setq cider-inject-dependencies-at-jack-in t)`. I get the same error if I set the var to `nil` and manually set `cider-nrepl` in my `profiles.clj`.

## Expected behavior

Running `cider-jack-in` should work :) 

## Actual behavior

A get the following error:

````
Starting nREPL server via /usr/local/bin/lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.12\"\] -- update-in :plugins conj \[refactor-nrepl\ \"2.3.0-SNAPSHOT\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.13.0-SNAPSHOT\"\] -- repl :headless...
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: resources/see-also.edn (No such file or directory), compiling:(info.clj:143:38)
 at clojure.lang.Compiler$InvokeExpr.eval (Compiler.java:3657)
    clojure.lang.Compiler$NewExpr.eval (Compiler.java:2568)
    clojure.lang.Compiler$InvokeExpr.eval (Compiler.java:3651)
    clojure.lang.Compiler$DefExpr.eval (Compiler.java:451)
    clojure.lang.Compiler.eval (Compiler.java:6932)
    clojure.lang.Compiler.load (Compiler.java:7379)
    clojure.lang.RT.loadResourceScript (RT.java:372)
    clojure.lang.RT.loadResourceScript (RT.java:363)
    clojure.lang.RT.load (RT.java:453)
    clojure.lang.RT.load (RT.java:419)
    clojure.core$load$fn__5677.invoke (core.clj:5893)
    clojure.core$load.invokeStatic (core.clj:5892)
    clojure.core$load.doInvoke (core.clj:5876)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invokeStatic (core.clj:5697)
    clojure.core$load_one.invoke (core.clj:5692)
    clojure.core$load_lib$fn__5626.invoke (core.clj:5737)
    clojure.core$load_lib.invokeStatic (core.clj:5736)

````
## Steps to reproduce the problem

Start a new Leiningen project with `lein new test-app`. Run the command created by cider:

`lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.12\"\] -- update-in :plugins conj \[refactor-nrepl\ \"2.3.0-SNAPSHOT\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.13.0-SNAPSHOT\"\] -- repl :headless`

### cider-nrepl version

0.13.0-SNAPSHOT as suggested by Cider.

### Java version

1.8

### Operating system

OS X El Capitano

**Comment by arrdem** [comment]
Beat me by 31 seconds. This is #353 acting up/being broken.

**Comment by arrdem** [comment]
https://github.com/clojure-emacs/cider-nrepl/pull/353/commits/e6f36096696794eac9a6727d61ed780904b74d7d#diff-7e5759ae416dd076f6227ef23d80414dR143

Yeah that uh doesn't work in production mate.

**Comment by sarith** [comment]
This is my first day with Clojure (ever).  What's the quickest way for me to workaround this?  I see that you merged a fix - how I do I apply this? I'm using Emacs (spacemacs).

**Comment by bbatsov** [comment]
I fix was recently pushed to prod. You'll have to use `lein -U` to update your local snapshots (lein updates them just once a day by default for some crazy reason).

**Comment by sarith** [comment]
@bbatsov You guys are so on point - thanks :)  Working now.
