### ISSUE TITLE
Provide a way to opt out of nrepl middleware

### ISSUE THREAD

**Issue by kurtwheeler** [clojure-emacs/cider-nrepl#359]
Hello. I'd like to be able to not have any of the `middleware.out` code run. I like having my output go to stdout. I have been unable to find a way to unset the behavior that the `middleware.out` specifies.

I've tried resetting the value of `*out*` with:
```
(do
  (require '[cider.nrepl.middleware.out])
  (alter-var-root #'*out* (constantly cider.nrepl.middleware.out/original-out))
```

but that didn't work.

## Expected behavior
`(println "hi")` prints a line to stdout

## Actual behavior
`(println "hi")` prints a line to the Cider REPL.

## Steps to reproduce the problem
1. Start an app which launches an NREPL server.
2. Connect emacs to that NREPL server using cider-mode
3. Evaluate a form `(println "hi")`.

### cider-nrepl version

0.11.0

### Java version

1.7

### Operating system

Xubuntu

Thanks for any help, support, or insight you can provide for this use case!

**Comment by Malabarba** [comment]
The out middleware is not suppose to hide output from stdout. That is, it should print to *both* the repl and stdout. Is that the behaviour you get?

**Comment by kurtwheeler** [comment]
Oh really? Hmm okay so I think I have misunderstood the issue. It seems like this is probably a bug then because I can get text to stdout if I put a print statement somewhere that will be evaluated by my app without a `cider-eval` occurring. However any prints within a form that I use cider-emacs to evaluate won't send their output to stdout.

My initial testing is still valid. It seems like the crux of this issue is that evaluating `(println "hi")` won't cause "hi\n" to be sent to stdout, instead it only goes to the REPL.

**Comment by Malabarba** [comment]
Ah. That's not the `out` middleware, and it's not due to cider. That's just standard `tools.nrepl` behaviour.
There might a way to get around it, but I'm not sure how.

**Comment by kurtwheeler** [comment]
Oh I see. Well that points me in the right direction at least. Thanks for your help. I guess this can be closed then.

**Comment by Malabarba** [comment]
No problem. Hope you find a way. :+1:
