### ISSUE TITLE
Update compliment to 0.3

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider-nrepl#363]
The only stopper for the next stable release is that we have to update compliment to version 0.3 (and we need a stable release of it). 0.3 introduced some breaking changes, so this is going to require a bit of work.

Alternatively we can ship with 0.2.8 (but it never got a stable release).

I'm extremely busy these days, so I'd be thankful if someone else can take a look at this. @cskksc can you try to do the update?

//cc @alexander-yakushev

**Comment by cskksc** [comment]
@bbatsov I'd be happy to do it :-). I'll take a look at the required changes and update here with some rough timelines.

**Comment by bbatsov** [comment]
Thanks! When the update is ready we'll just have to ping @alexander-yakushev to cut a stable release of 0.3.

**Comment by alexander-yakushev** [comment]
Just saying, there shouldn't be any breaking changes for those who already used `:tag-candidates true`. It has just become the default behaviour.

**Comment by bbatsov** [comment]
We aren't using it. :-)

On Monday, 11 July 2016, Alexander Yakushev <notifications@github.com>
wrote:

> Just saying, there shouldn't be any breaking changes for those who already
> used :tag-candidates true. It has just become the default behaviour.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/clojure-emacs/cider-nrepl/issues/363#issuecomment-231811144>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAGVyrDz1CaDFJaVOQeTo88irVOIrrbhks5qUoJTgaJpZM4JHxqp>
> .
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by alexander-yakushev** [comment]
Wanna bet? :grin: 
https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/complete.clj#L20

**Comment by cskksc** [comment]
@alexander-yakushev The only change is that `compliment.sources.resources/resources-by-prefix` has been deprecated in favor of `completions`. Everything else just works. I am trying to parse the context in the case of `io/resource "|"`, so it can use the auto-completion feature. CIDER only handles `context` in lists now.

**Comment by cskksc** [comment]
I forgot to say the `resources-list` op works by using `(jvm-complete/completions "" {:context context :sources [::r/resources]})`, but I'm just trying to make the auto-complete work for this too.

**Comment by bbatsov** [comment]
Guess we can close this. @alexander-yakushev please, cut a stable release.

**Comment by alexander-yakushev** [comment]
@bbatsov Done!
