### ISSUE TITLE
Middleware tests would build a jar and test it

### ISSUE THREAD

**Issue by ckoparkar** [clojure-emacs/cider-nrepl#367]
CIDER faced some downtime on May 11, due to a bug in the middleware. It affected all users, as the middleware wouldn't start at all, and required a hotfix and a clojars deployment. We need to improve the tests, so that it would build the jar and test it against some application.

I guess we should tackle this before the 0.14 release. Creating a ticket here so that we don't forget :-)

Relevant slack conversation:

```
arrdem     [17:35:34] It would be nice if the tests actually built and ran there jar so this doesn't happen again. I may take a swing at that later.
bozhidar   [17:56:52] hehe
bozhidar   [17:56:58] I wouldn’t mind this
bozhidar   [17:57:20] getting travis involved in the deployment has been on my todo for a while
agile_geek [19:47:30] circleci is nice too
bozhidar   [20:46:34] guess so
bozhidar   [20:47:08] I just use travis by default, as a few years ago it was the only ci with the explicit goal of providing trivial github integration
malabarba  [21:09:22] We could set up an instance on AWS that builds and deploys the latest master. Travis already lets you ping a webhook when all builds pass, so they'd be trivial to integrate.
malabarba  [21:10:40] And AWS instances are pretty cheap AFAIK, so it wouldn't take a noticeable bite out of the donations.
dpsutton   [21:42:33] I'd be down with sponsoring a year of that
dpsutton   [21:42:49] if you can estimate the cost I can make a contribution of that amount
```

Full conversation [here](https://clojurians-log.clojureverse.org/cider/2016-05-11.html).

**Comment by bbatsov** [comment]
@gonewest818 has implemented the auto-deployment, but I wonder what to do about the "integration" test. I guess we can just boot someone an nREPL with the middleware to see if it starts or something like this.

**Comment by gonewest818** [comment]
With ecukes, maybe.

**Comment by bbatsov** [comment]
I think the suggestion here is just to test that `cider-nrepl` is not completely broken, not to actually test some integration with CIDER.

**Comment by ckoparkar** [comment]
Woo!
