### ISSUE TITLE
Running tests for a clojure.spec instrumented NS fails

### ISSUE THREAD

**Issue by sundbp** [clojure-emacs/cider-nrepl#369]
## Expected behavior
Tests to run as normal :)

## Actual behavior
An exception is thrown related to cider-nrepl middleware.

## Steps to reproduce the problem
Run any clojure.test test for an NS that has been insturmented via clojure.spec.test/instrument.

## Environment & Version information
;; CIDER 0.13.0 (package: 20160725.136) (California), nREPL 0.2.12
;; Clojure 1.9.0-alpha10, Java 1.8.0_92

### Operating system
OSX

## Example stack trace
Show: Clojure Java REPL Tooling Duplicates All  (32 frames hidden)

2. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling clojure/test/check/clojure_test.cljc at (95:1)

1. Caused by java.lang.ClassCastException
   cider.nrepl.middleware.test$report cannot be cast to
   clojure.lang.MultiFn
   
                  core.clj: 1806  clojure.core/get-method
                  core.clj: 1806  clojure.core/get-method
         clojure_test.cljc:   95  clojure.test.check.clojure_test$eval169739/invokeStatic
         clojure_test.cljc:   95  clojure.test.check.clojure_test$eval169739/invoke
             Compiler.java: 6946  clojure.lang.Compiler/eval
             Compiler.java: 7398  clojure.lang.Compiler/load
                   RT.java:  374  clojure.lang.RT/loadResourceScript
                   RT.java:  365  clojure.lang.RT/loadResourceScript
                   RT.java:  455  clojure.lang.RT/load
                   RT.java:  421  clojure.lang.RT/load
                  core.clj: 6007  clojure.core/load/fn
                  core.clj: 6006  clojure.core/load
                  core.clj: 5990  clojure.core/load
               RestFn.java:  408  clojure.lang.RestFn/invoke
                  core.clj: 5811  clojure.core/load-one
                  core.clj: 5806  clojure.core/load-one
                  core.clj: 5851  clojure.core/load-lib/fn
                  core.clj: 5850  clojure.core/load-lib
                  core.clj: 5831  clojure.core/load-lib
               RestFn.java:  142  clojure.lang.RestFn/applyTo
                  core.clj:  659  clojure.core/apply
                  core.clj: 5888  clojure.core/load-libs
                  core.clj: 5872  clojure.core/load-libs
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  659  clojure.core/apply
                  core.clj: 5910  clojure.core/require
                  core.clj: 5910  clojure.core/require
               RestFn.java:  482  clojure.lang.RestFn/invoke
                check.cljc:   10  clojure.test.check$eval169702$loading__7482__auto____169703/invoke
                check.cljc:   10  clojure.test.check$eval169702/invokeStatic
                check.cljc:   10  clojure.test.check$eval169702/invoke
             Compiler.java: 6946  clojure.lang.Compiler/eval
             Compiler.java: 6935  clojure.lang.Compiler/eval
             Compiler.java: 7398  clojure.lang.Compiler/load
                   RT.java:  374  clojure.lang.RT/loadResourceScript
                   RT.java:  365  clojure.lang.RT/loadResourceScript
                   RT.java:  455  clojure.lang.RT/load
                   RT.java:  421  clojure.lang.RT/load
                  core.clj: 6007  clojure.core/load/fn
                  core.clj: 6006  clojure.core/load
                  core.clj: 5990  clojure.core/load
               RestFn.java:  408  clojure.lang.RestFn/invoke
                  core.clj: 5811  clojure.core/load-one
                  core.clj: 5806  clojure.core/load-one
                  core.clj: 5851  clojure.core/load-lib/fn
                  core.clj: 5850  clojure.core/load-lib
                  core.clj: 5831  clojure.core/load-lib
               RestFn.java:  142  clojure.lang.RestFn/applyTo
                  core.clj:  659  clojure.core/apply
                  core.clj: 5888  clojure.core/load-libs
                  core.clj: 5872  clojure.core/load-libs
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  659  clojure.core/apply
                  core.clj: 5910  clojure.core/require
                   gen.clj:   18  clojure.spec.gen/dynaload
                   gen.clj:   26  clojure.spec.gen/fn
                   gen.clj:   26  clojure.spec.gen/fn
                Delay.java:   37  clojure.lang.Delay/deref
                  core.clj: 2309  clojure.core/deref
                   gen.clj:   27  clojure.spec.gen/quick-check
                  spec.clj: 1502  clojure.spec/validate-fn
                  spec.clj: 1520  clojure.spec/fspec-impl/reify
                  spec.clj:  117  clojure.spec/conform
                  spec.clj:  677  clojure.spec/dt
                  spec.clj:  673  clojure.spec/dt
                  spec.clj: 1301  clojure.spec/deriv
                  spec.clj: 1308  clojure.spec/deriv
                  spec.clj: 1431  clojure.spec/re-conform
                  spec.clj: 1471  clojure.spec/regex-spec-impl/reify
                  spec.clj:  117  clojure.spec/conform
                  test.clj:  120  clojure.spec.test/spec-checking-fn/conform!
                  test.clj:  139  clojure.spec.test/spec-checking-fn/fn
               RestFn.java:  436  clojure.lang.RestFn/invoke
           time_series.clj:  947  tulos.kuva.time-series/arithmetic-op
           time_series.clj:  944  tulos.kuva.time-series/arithmetic-op
           time_series.clj:  955  tulos.kuva.time-series/plus
           time_series.clj:  951  tulos.kuva.time-series/plus
               RestFn.java:  421  clojure.lang.RestFn/invoke
      time_series_test.clj:  202  tulos.kuva.time-series-test/fn
[test of trace cut]

**Comment by sebastianpoeplau** [comment]
The issue seems to be caused by a conflict with spec's lazy loading of `test.check` - see [this ticket for a similar crash with `lein test`](http://dev.clojure.org/jira/browse/TCHECK-113). I've been able to avoid the problem by explicitly requiring a namespace from `test.check` instead of having spec load it for me. Alternatively, see the suggestions on the ticket.

**Comment by sundbp** [comment]
That did help with that exception. I do run into another exception, seemingly related to having fdef'd a defmulti, but that's obviously unrelated to cider. Thanks!
