### ISSUE TITLE
Usual post-release "no N.M+1.0-SNAPSHOT" ticket

### ISSUE THREAD

**Issue by arrdem** [clojure-emacs/cider-nrepl#370]
As of right now CIDER snapshot which I'm crazy enough to run is trying to inject `[cider-nrepl "1.4.0-SNAPSHOT"]` which of course doesn't exist. Having melpa-unstable be usable again would be nice ❤️

**Comment by samestep** [comment]
This isn't fixed; the same [error] still occurs because 0.14.0-SNAPSHOT has not been pushed to [Clojars].

[clojars]: https://clojars.org/cider/cider-nrepl
[error]: https://github.com/clojure-emacs/cider/issues/1816

**Comment by expez** [comment]
https://clojars.org/cider/cider-nrepl/versions/0.14.0-SNAPSHOT
