### ISSUE TITLE
Debugger breaks on macros that require &env (like async.core/go)

### ISSUE THREAD

**Issue by kuberlog** [clojure-emacs/cider-nrepl#372]
```
>> (defn [foo] (go [] foo))
```

This will crash 0.14.0-SNAPSHOT

An issue is open in cider repo that provides more information. https://github.com/clojure-emacs/cider/issues/1775

The basic fix is to use https://github.com/ztellman/riddley as the macroexpander instead of walk/macroexpand-all

I have already written a patch. It seems to work on my machine. There is one problem, which is that the original form does not get saved into metadata as `::original-form`. I will submit a pull request, but perhaps this part will need to be fixed.

**Comment by bbatsov** [comment]
@Malabarba Guess you'll have to take a look at the proposed solution.

**Comment by royalaid** [comment]
Any status updates on this issue?

**Comment by Malabarba** [comment]
Not from me, sorry. 😢

**Comment by vemv** [comment]
See also https://github.com/clojure-emacs/orchard/issues/77#issuecomment-1013812498

**Comment by vemv** [comment]
As some additional info, looks like with project Loom, the `go` macro will be fundamentally simpler, so we might get a 80% solution for free.

Also, anyway `go` is backed by a thread pool (today and also after Loom), and the debugger doesn't support arbitrary threads https://github.com/clojure-emacs/cider-nrepl/issues/630#issuecomment-524857244, so maybe `&env` wouldn't have given us that much.
