### ISSUE TITLE
Refresh reloads too many namespaces

### ISSUE THREAD

**Issue by jcf** [clojure-emacs/cider-nrepl#376]
## Expected behavior

Running `cider-refresh` refreshes my application source code, and not third-party libraries like Component or Sente.
## Actual behavior

Component and Sente namespaces are being refreshed.
## Steps to reproduce the problem

Tricky. Setup a new application with both `clj` and `cljs` files in `src`, and output your compiled Clojurescript to `resources`. Add some Clojurescript libraries like Sente and Component and refresh your namespaces. You'll see output like this:

```
cider-refresh: Reloading (inno.ws inno.bootstrap taoensso.sente.interfaces taoensso.sente.packers.transit taoensso.sente inno.listener inno.timbre inno.system inno.config user inno.main)
```

The Sente namespaces shouldn't get refreshed. They come from a a library I've pulled into my app.

I believe using the following snippet helps, but I'd need to start adding Sente et al to avoid Cider refreshing more that it should.

``` clj
(doseq [sym ['com.stuartsierra.component
             'com.stuartsierra.dependency]
        :let [ns (find-ns sym)]
        :when ns]
  (clojure.tools.namespace.repl/disable-reload! ns))
```

There's an open issue on [component](https://github.com/stuartsierra/component/issues/45#issuecomment-245052313) that I think may be related to this because I only have problems with my system definition (which is held in the `reloaded.repl/system` var) when refreshing with Cider; `clojure.tools.namespace.repl/refresh` works as expected.
### Version info

```
;; CIDER 0.14.0snapshot (package: 20160830.23), nREPL 0.2.12
;; Clojure 1.9.0-alpha12, Java 1.8.0_60
```
### Operating system

```
Darwin mbp.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,5 Darwin
```

**Comment by SevereOverfl0w** [comment]
This is a bug in TNS https://dev.clojure.org/jira/browse/TNS-45
