### ISSUE TITLE
Could not find artifact cider-nrepl 0.15.0-SNAPSHOT in clojars

### ISSUE THREAD

**Issue by hughjfchen** [clojure-emacs/cider-nrepl#380]
When I tried to launch cider within emacs,I got following error message:
Could not find artifact cider:cider-nrepl:jar:0.15.0-SNAPSHOT in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.

## Expected behavior
I expected the cider can launched without any errors.

## Actual behavior
But I got following error message:
Could not find artifact cider:cider-nrepl:jar:0.15.0-SNAPSHOT in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.

## Steps to reproduce the problem
1.Upgrade cider from within emacs to the latest version
2.open a clojure source code file
3.tried to launch repl by C c M j
4.you got the above error message

## Environment & Version information
emacs 25.1
cider 0.15.0-SNAPSHOT
nrepl 0.2.12
cider-nrepl 0.15.0-SNAPSHOT

### cider-nrepl version
0.15.0-SNAPSHOT

### Java version

1.8

### Operating system

ArchLinux

**Comment by expez** [comment]
Deployed.  

Please re-open if there are any issues.

**Comment by bbatsov** [comment]
That's odd. I had deployed this in the morning after noticing I forgot to do it yesterday.

**Comment by expez** [comment]
Perhaps it already was deployed and it really was a network problem.
