### ISSUE TITLE
cider-nrepl not capturing some boot output

### ISSUE THREAD

**Issue by arrdem** [clojure-emacs/cider-nrepl#381]
See https://github.com/adzerk-oss/boot-cljs/issues/138 reported by @agzam on slack.

**Comment by bhagany** [comment]
This is fixed here: https://github.com/clojure-emacs/cider-nrepl/pull/387

**Comment by bbatsov** [comment]
@bhagany You might want to mention your fix in CIDER's changelog as it's pretty important.

**Comment by bhagany** [comment]
okay, will do

**Comment by arrdem** [comment]
Awesome! Thanks @bhagany for the work.

**Comment by oliyh** [comment]
Hi @bhagany,

I think this has resulted in some undesired behaviour for us. We’re using `clojure.tools.logging` with `logback` and the `ConsoleAppender`.

Our logs, which used to go to `*nrepl-server*` only, now go to `*cider-repl*` *as well*.

Here are our logging deps:
```clojure
[org.clojure/tools.logging "0.3.1"]
[org.slf4j/jul-to-slf4j "1.7.22"]
[ch.qos.logback/logback-classic "1.1.8" :exclusions [org.slf4j/slf4j-api]]
```

logback.xml:

```
<configuration scan="true" scanPeriod="10 seconds">

  <!-- Console output -->
  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">

    <!-- encoder defaults to ch.qos.logback.classic.encoder.PatternLayoutEncoder -->
    <encoder>
      <pattern>%date{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg severity=%level, namespace=%logger, %mdc%n</pattern>
    </encoder>
  </appender>

  <root level="INFO">
    <appender-ref ref="STDOUT" />
  </root>

</configuration>
```

And the behaviour we see is:
```clojure
user> (clojure.tools.logging/warn "hi")
2017-01-03 13:38:23.432 [nREPL-worker-16] WARN  user - hi severity=WARN, namespace=user,
nil

user> (println "hi")
hi
nil
```

We only expect `println` to go to the REPL and all log statements to go to `*nrepl-server*` only. We’re being flooded by our own log messages now in the REPL.

Can you suggest a workaround or change to accommodate our use case?

Thanks
