### ISSUE TITLE
Erroneous warnings about Clojure version on cider-jack-in without project

### ISSUE THREAD

**Issue by raxod502** [clojure-emacs/cider-nrepl#384]
(Wait—I just realized that this is an error from refactor-nrepl, not cider-nrepl. Shall I report the issue there instead?)

## Expected behavior

`M-x cider-jack-in` should work correctly outside of a Clojure project, as well as inside one.

## Actual behavior

When not inside a Clojure project, the REPL still starts but warnings from `refactor-nrepl` are printed to `*nrepl-server*`. See below.

## Steps to reproduce the problem

Make sure you are **not** inside a Clojure project. The error does not occur when inside a project.

```
emacs -Q
M-x package-initialize RET
M-x cider-jack-in RET y
C-x b *nrepl-server* RET
```

Contents of buffer:

```
Warning: refactor-nrepl requires org.clojure/clojure 1.7.0 or greater.
Warning: refactor-nrepl middleware won't be activated due to missing dependencies.
Warning: refactor-nrepl requires org.clojure/clojure 1.7.0 or greater.
Warning: refactor-nrepl middleware won't be activated due to missing dependencies.
Warning: refactor-nrepl requires org.clojure/clojure 1.7.0 or greater.
Warning: refactor-nrepl middleware won't be activated due to missing dependencies.
nREPL server started on port 49162 on host 127.0.0.1 - nrepl://127.0.0.1:49162
```

### cider-nrepl version

0.15.0-SNAPSHOT, the version injected by CIDER

### Java version

1.8.0_31

### Clojure version

1.8.0

### Operating system

El Capitan 10.11.6

### profiles.clj

None.

### Emacs packages

Installed from MELPA.

## Related

#279. Note that the error reproduces if I take the command CIDER uses for `cider-jack-in` and just run it in a terminal—the same warnings are printed, although the REPL still starts OK.

**Comment by expez** [comment]
Opening an issue against the other repo would be preferable.

That said, you're already getting the expected behavior.  Everything works, but refactor-nrepl is disabled because it cannot do any meaningful work without being in the context of a project.

I think the warning could be greatly improved, though.

**Comment by raxod502** [comment]
Duly noted and relocated. But I find it hard to believe that `refactor-nrepl` would signal a warning that is factually incorrect (i.e. that the version of Clojure used for the REPL is less than 1.7.0) unless there were something more seriously wrong.

Especially given that the warning can be resolved as follows:

```
(setq cider-jack-in-auto-inject-clojure 'latest)
```
