### ISSUE TITLE
Refresh doesn't work on boot projects

### ISSUE THREAD

**Issue by SevereOverfl0w** [clojure-emacs/cider-nrepl#385]
## Expected behavior
operation refresh would refresh namespaces
## Actual behavior
operation refresh refreshes no namespaces
## Steps to reproduce the problem

```
boot -d seancorfield/boot-new new -t app -n myapp
cd myapp
boot repl # (or boot cider repl, depending on your setup)
```
_run refresh in your preferred way_

## Environment & Version information
Boot 2.6.0

### cider-nrepl version

0.14.0

### Java version

1.8

### Operating system

Linux

---

This is caused by how c.t.n gets the classpath, solutions are to:
1. Upgrade to 0.3.0-alpha3 of c.t.n
2. https://github.com/Deraen/boot-ctn/blob/master/src/deraen/boot_ctn.clj run something like this when detecting inside a boot project

**Comment by arichiardi** [comment]
Yep, I like this! I would take the code @Deraen used in his task and port it to `cider`. The advantage is no more `boot-ctn` additional call and therefore a smoother experience for `boot` users. Definitely worth a patch.

**Comment by Deraen** [comment]
As a note, I don't use that code myself anymore, instead I depend on 0.3.0-alpha3 c.t.n everywhere.
