### ISSUE TITLE
Error running individual test files

### ISSUE THREAD

**Issue by dpsutton** [clojure-emacs/cider-nrepl#390]
## Expected behavior

```
cider-nrepl|master⚡ ⇒lein with-profile +test-clj test
....

Ran 175 tests containing 1095 assertions.
0 failures, 0 errors.
```

This makes me think that all tests pass and that running the tests in an individual file would pass:

```
cider-nrepl|master⚡ ⇒lein with-profile +test-clj test test/clj/cider/nrepl/middleware/track_state_test.clj 
```

Or so you would think.

## Actual behavior

```
cider-nrepl|master⚡ ⇒lein with-profile +test-clj test test/clj/cider/nrepl/middleware/track_state_test.clj 

lein test cider.nrepl.middleware.track-state-test

lein test :only cider.nrepl.middleware.track-state-test/update-and-send-cache-test

FAIL in (update-and-send-cache-test) (track_state_test.clj:32)
expected: (> (count new-data) 100)
  actual: (not (> 64 100))

lein test :only cider.nrepl.middleware.track-state-test/update-and-send-cache-test

FAIL in (update-and-send-cache-test) (track_state_test.clj:36)
expected: (> (count changed-namespaces) 100)
  actual: (not (> 64 100))

Ran 7 tests containing 32 assertions.
2 failures, 0 errors.
Tests failed.
Error encountered performing task 'test' with profile(s): 'base,system,user,provided,dev,test-clj'
Tests failed.
cider-nrepl|master⚡ ⇒ 
```

## Steps to reproduce the problem
The above commands are how I reproduced it. Running all tests yields no failures. Running individual files yields failures. Not a fan :)

Its tough since we are running tests on inspectors and its getting info about loaded namespaces and such. But the fact that a test might need to run after a few other tests run is certainly a code smell :)

### cider-nrepl version

tracking master

### Java version

1.8

### Operating system
fedora 25

**Comment by bbatsov** [comment]
Yeah, this will need to be fixed.

**Comment by bbatsov** [comment]
I think this was fixed at some point.
