### ISSUE TITLE
Message ops?

### ISSUE THREAD

**Issue by vspinu** [clojure-emacs/cider-nrepl#407]
Is there a way to trigger emacs to display a message or a warning?

**Comment by bbatsov** [comment]
Nope. Right now we have something like this only for errors, but building something similar for messages and warnings should be easy IMO.

**Comment by vspinu** [comment]
Ok. I will have a look. 

Any preference of how should it be signaled? Part of `status` or a specific slot (msg?) in response dict?

**Comment by vspinu** [comment]
Given that the direction taken in [nrepl clinet](https://github.com/vspinu/cider/blob/master/nrepl-client.el#L775-L786) is to dispatch on status. I guess proper handling would be to allow for two new statuses "message" and "warning". On both there will be a slot "msg" giving actual message. Sounds ok?
