### ISSUE TITLE
forms-str does not match arglists-str

### ISSUE THREAD

**Issue by xiongtx** [clojure-emacs/cider-nrepl#411]
## Expected behavior

The format of `:forms-str` from `cider.nrepl.middleware.info/format-response` should match that of `arglist-str`.

CIDER's `cider-docview-render-info`, for example, [treats them the same](https://github.com/clojure-emacs/cider/blob/v0.14.0/cider-doc.el#L417).

## Actual behavior

The value of [`:forms-str`](https://github.com/clojure-emacs/cider-nrepl/blob/v0.14.0/src/cider/nrepl/middleware/info.clj#L283) does not match that of [`:arglist-str`](https://github.com/clojure-emacs/cider-nrepl/blob/v0.14.0/src/cider/nrepl/middleware/info.clj#L281).

For `:forms-str`,

- There are two leading spaces
- Forms are joined with newlines

This causes forms to be rendered incorrectly in the doc buffer by `cider-docview-render-info`.

It's not clear why this is the case. Where are the leading spaces and newlines used?

## Steps to reproduce the problem

Not necessary.

### cider-nrepl version

`0.14.0`

### Java version

`openjdk version "1.8.0_111"`

### Operating system

`Fedora 24`

**Comment by bbatsov** [comment]
> It's not clear why this is the case. Where are the leading spaces and newlines used?

I don't remember anymore. Maybe we were trying to emulate how functions like `doc` display this. Someone should take a close look into this.
