### ISSUE TITLE
`src/cider/tasks.clj` requires `boot`, but project does not depend on it

### ISSUE THREAD

**Issue by xiongtx** [clojure-emacs/cider-nrepl#418]
## Expected behavior

[`src/cider/tasks.clj`](https://github.com/clojure-emacs/cider-nrepl/blob/6ace734fc22ba094ac3dbaf6afd3a032fa28eb24/src/cider/tasks.clj#L2) uses `boot.core`, etc., so `cider-nrepl` shoudl have a dependency on `boot`.

Otherwise, `cider-refresh` fails on `tasks.clj`.

## Actual behavior

There is [no dependency](https://github.com/clojure-emacs/cider-nrepl/blob/6ace734fc22ba094ac3dbaf6afd3a032fa28eb24/project.clj#L9) on `boot`.

## Steps to reproduce the problem

- Check out `cider-nrepl`
- `cider-jack-in`
- `cider-refresh`

### cider-nrepl version

Commit [6ace734fc22ba094ac3dbaf6afd3a032fa28eb24](https://github.com/clojure-emacs/cider-nrepl/tree/6ace734fc22ba094ac3dbaf6afd3a032fa28eb24)

### Java version

```
openjdk version "1.8.0_111"
```

### Operating system

```
Fedora 24
```

**Comment by bbatsov** [comment]
Let's add @arichiardi to this conversation, as I don't know what he had in mind. In general it doesn't seem right to add a depedency to boot, just to address this.

**Comment by arichiardi** [comment]
Uhm, this probably needs a dynamic loading then, I wonder why `cider-refresh` fails still. Maybe it should avoid refreshing `cider-nrepl` namespaces? They are tooling after all...

**Comment by bbatsov** [comment]
> Uhm, this probably needs a dynamic loading then, I wonder why cider-refresh fails still. Maybe it should avoid refreshing cider-nrepl namespaces? They are tooling after all...

@xiongtx was working on `cider-nrepl`. :-) `cider-refresh` is pretty useful when you do this. 

Maybe this should be moved to some standalone plugin for `boot`? Not really sure what's the best course of action here...

**Comment by arichiardi** [comment]
On June 27, 2017 7:29:13 AM PDT, Bozhidar Batsov <notifications@github.com> wrote:
>> Uhm, this probably needs a dynamic loading then, I wonder why
>cider-refresh fails still. Maybe it should avoid refreshing cider-nrepl
>namespaces? They are tooling after all...
>
>@xiongtx was working on `cider-nrepl`. :-) `cider-refresh` is pretty
>useful when you do this. 
>
>Maybe this should be moved to some standalone plugin for `boot`? Not
>really sure what's the best course of action here...
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/clojure-emacs/cider-nrepl/issues/418#issuecomment-311376012

Oh ok then it breaks 😀

Too many moving parts if you take it out I guess...if we are devving cider-nrepl we kind of accept some bumps I guess? For the sake of others, the namespace can be removed temporarily from the repo. It is never called directly but only on jack-in.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by arichiardi** [comment]
On June 27, 2017 7:29:13 AM PDT, Bozhidar Batsov <notifications@github.com> wrote:
>> Uhm, this probably needs a dynamic loading then, I wonder why
>cider-refresh fails still. Maybe it should avoid refreshing cider-nrepl
>namespaces? They are tooling after all...
>
>@xiongtx was working on `cider-nrepl`. :-) `cider-refresh` is pretty
>useful when you do this. 
>
>Maybe this should be moved to some standalone plugin for `boot`? Not
>really sure what's the best course of action here...
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/clojure-emacs/cider-nrepl/issues/418#issuecomment-311376012

Or we add it as dev dependency
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SevereOverfl0w** [comment]
https://github.com/ztellman/manifold/blob/c6217cbe35fda82f120ee6fcef3a48bfc9ca7202/src/manifold/utils.clj#L112-L118 manifold does dynamic loading like this. Afaik, it works well. It would solve the problem here I believe.
