### ISSUE TITLE
List resources includes cljc & cljs files

### ISSUE THREAD

**Issue by SevereOverfl0w** [clojure-emacs/cider-nrepl#458]
The list resources relies on compliment (why?) which filters the code files for us. It hasn't been updated to also filter these extensions.

The source code for list-resources looks like a bit of a hack which uses completion to get the results. Given my needs, I was thinking about an alternative form of list-resources (list-resource-urls) which didn't require a round-trip for getting the actual file path to the resource, and I could resolve this at the same time?

**Comment by bbatsov** [comment]
> The list resources relies on compliment (why?) which filters the code files for us. It hasn't been updated to also filter these extensions.

It was done like this just for sake of doing in quickly. Compliment had resource completion and it made sense to just reuse it instead of writing something else.

> The source code for list-resources looks like a bit of a hack which uses completion to get the results. Given my needs, I was thinking about an alternative form of list-resources (list-resource-urls) which didn't require a round-trip for getting the actual file path to the resource, and I could resolve this at the same time?

That's fine by me.
