### ISSUE TITLE
No way to use embedded cider-nrepl with other middleware

### ISSUE THREAD

**Issue by SevereOverfl0w** [clojure-emacs/cider-nrepl#464]
The middleware stack is now a resolved list. If I want to use cider-nrepl with refactor-nrepl, I end up with this:

```
(conj (map #'cider.nrepl/resolve-or-fail cider.nrepl/cider-middleware)
      refactor.nrepl/wrap-refactor)
```

This uses a private var, so is not particularly preferable. I think a function which returns the resolved list should be added to cider.nrepl.

**Comment by bbatsov** [comment]
Yeah, that makes perfect sense.

**Comment by bbatsov** [comment]
@SevereOverfl0w Mind sending a PR about this?
