### ISSUE TITLE
Fix info-clj in info middleware to correctly return information on different kinds of objects

### ISSUE THREAD

**Issue by jpmonettas** [clojure-emacs/cider-nrepl#468]
Currently no spec is returned for clojure.core/let symbol given that there is a spec in the registry for it.

```clojure
user> (:spec (cider.nrepl.middleware.info/info-clj 'clojure.core 'let))
;; => nil
> (clojure.spec.alpha/spec 'clojure.core/let)
;; => #object[clojure.spec.alpha$fspec_impl$reify__1215 0x75789318 "clojure.spec.alpha$fspec_impl$reify__1215@75789318"]
```
Looking at cider.nrepl.middleware.info/info-clj
```clojure
(defn info-clj
  [ns sym]
  (or
     ;; it's a special (special-symbol? or :special-form)
    (m/special-sym-meta sym)
    ;; it's a var
    (m/var-meta (m/resolve-var ns sym))
    ;; sym is an alias for another ns
    (m/ns-meta (get (m/resolve-aliases ns) sym))
    ;; it's simply a full ns
    (m/ns-meta (find-ns sym))
    ;; it's a Java class/member symbol...or nil
    (java/resolve-symbol ns sym)))
``` 
we return different kind of information for different kinds of objects represented by the symbol.
For example `clojure.core/let` (a symbol that represents a var) is being treated as a "special form" instead of a macro, so no spec info.

What I find very confusing in Clojure documentation is the use of "special form" which is not a concept, just an annotation on vars (always macros) that are special forms in other lisps.

In Clojure, real "special forms" are called special symbols:

```clojure
user> (keys (. clojure.lang.Compiler specials))
(&
 let*
 monitor-exit
 case*
 fn*
 try
 reify*
...
)
``` 
and even if the oficial documentation says let is a special form, it isn't special at all, let* is, while let is just a macro.

Looking at Clojure code I couldn't find any use of :special-form annotation apart from printing a label at the repl doc.

I think the cleanest way to branch info-clj is to forget about the "special form" thing and say a symbol could be one of :
- special symbol 
- a var
- a namespace
- a java thing

The only things that are annotated under special-forms in Clojure are : 
clojure.core/let
clojure.core/fn
clojure.core/letfn
clojure.core/loop

**Comment by bbatsov** [comment]
That's fine by me.
