### ISSUE TITLE
Spec middleware spec-form doesn't return anonymous functions correctly

### ISSUE THREAD

**Issue by jpmonettas** [clojure-emacs/cider-nrepl#470]
A spec like 
```clojure
(s/def ::example-one-args (s/and #(< (:start %) (:end %))))
(spec-form ":cider.nrepl.middleware.spec/example-one-args")

;; => 

("clojure.spec.alpha/and"
 ("clojure.core/fn"
  ["%"]
  ("clojure.core/<" (":start" "%") (":end" "%"))))
```
while a spec like 
```clojure
(s/fdef example-one
        :args (s/and #(< (:start %) (:end %))))
(spec-form "cider.nrepl.middleware.spec/example-one")

;; =>

("clojure.spec.alpha/fspec"
 ":args"
 ("clojure.spec.alpha/and"
  ("fn*"
   ["p1__22142#"]
   ("clojure.core/<" (":start" "p1__22142#") (":end" "p1__22142#")))))
```

**Comment by jpmonettas** [comment]
This is happening because (clojure.spec.alpha/form ...) is returning differently in different situations.

(s/def ::example-one-args (s/and #(< (:start %) (:end %))))
(s/form ::example-one-args)
;; => (clojure.spec.alpha/and (clojure.core/fn [%] (clojure.core/< (:start %) (:end %))))

(s/fdef example-one
        :args (s/and #(< (:start %) (:end %))))
(s/form 'pretty-spec.core/example-one)
;; => (clojure.spec.alpha/fspec :args (clojure.spec.alpha/and (fn* [p1__22097#] (clojure.core/< (:start p1__22097#) (:end p1__22097#)))))

;; just removing the s/and shows fn with % instead of special symbol fn*
(s/fdef example-two
        :args #(< (:start %) (:end %)))
(s/form 'pretty-spec.core/example-two)
;; => (clojure.spec.alpha/fspec :args (clojure.core/fn [%] (clojure.core/< (:start %) (:end %))))

My approach would be to create something like `cider.nrepl.middleware.spec/normalize-fn-form` which walks down the form and moves everything to (fn [%] ...) notation.

@bbatsov @xiongtx please let me know your thoughts.

**Comment by bbatsov** [comment]
I'm fine with the suggested approach.
