### ISSUE TITLE
Tighten up the codecov.io data reporting

### ISSUE THREAD

**Issue by gonewest818** [clojure-emacs/cider-nrepl#495]
First of all, the [pull request](https://codecov.io/gh/clojure-emacs/cider-nrepl/pulls) view looks broken. Warnings of "missing base report" and pulls labeled "Untitled" when they certainly were titled. Maybe there's additional metadata we're supposed to be reporting in to make that a little cleaner.

<img width="1202" alt="screen shot 2018-01-26 at 9 07 54 am" src="https://user-images.githubusercontent.com/2460918/35451635-c00999d8-0278-11e8-86ac-54ff597c27a7.png">

Secondly, git commit data seems to be missing, and not limited to pull requests. Again, unclear if that's something we supply or something codecov.io is doing from their side. But needs investigation.

<img width="562" alt="screen shot 2018-01-26 at 9 11 54 am" src="https://user-images.githubusercontent.com/2460918/35451782-35b362f4-0279-11e8-8c39-2a01cae902e1.png">

Finally, once all this is cleaned up it might make sense to link the code coverage badge on README.md to that branch's specific report (https://codecov.io/gh/clojure-emacs/cider-nrepl/branch/master)

**Comment by gonewest818** [comment]
Hey, passing along the information I received from codecov support:

Codecov support wrote:
> Hey Neil,
>
> This happens when the user we have on file loses authentication to the repository. Please fix by following these directions: http://docs.codecov.io/docs/team-bot
> 
> After you set the bot or add Github Integration please submit a new commit to CI so Codecov may use the new bot to interact with your repository.
> 
> Thank you!
> Steve

which means, a project maintainer needs to follow the link and do as it says...

**Comment by bbatsov** [comment]
I've setup the GitHub integration for both repos - hopefully this is going to work fine now.
