### ISSUE TITLE
Use a standardized method to detect JDK version

### ISSUE THREAD

**Issue by ckoparkar** [clojure-emacs/cider-nrepl#500]
To quote @gonewest818, "we need a way to detect Oracle and OpenJDK versions and report back consistently". See this [discussion](https://github.com/clojure-emacs/cider-nrepl/pull/494#discussion_r16426233) for more details.

The JAVA_VERSION is used to do some JDK specific things (eg. filter out certain tests in orchard, add `:jvm-opts` in the nREPL etc.). There are some inconsistencies with the current method;

`(lein version | cut -d " " -f 5 | cut -d "." -f 1-2)`

| Environment | Script result |
| ------------- |:-------------:|
| My local m/c running Archlinux and OpenJDK | `9` |
| Travis CI infrastructure running Ubuntu 14.04| `9.0` |
| @gonewest818's experiment with a Docker container<br> running Ubuntu 16.04 and OpenJDK 9 | `9-internal`|

This is not a high priority ticket at the moment. But if the Travis tests start failing, this might be one reason why.

**Comment by gonewest818** [comment]
I'm toying with a Leiningen plugin that wraps `org.apache.commons.lang3.SystemUtils`. Exposing all the static fields in that class as a map so the caller can look up information about the Java environment as seen by Leiningen on your desktop or in your CI.

So hypothetically something like `lein sysutil :is-java-9` prints the value of `SystemUtils/IS_JAVA_9` for  debugging. Or assign the output to a shell variable and control script execution based on the result.

**Comment by gonewest818** [comment]
work in progress: https://github.com/gonewest818/lein-sysutils
