### ISSUE TITLE
Check if tools.jar is loaded before loading it

### ISSUE THREAD

**Issue by alexander-yakushev** [clojure-emacs/cider-nrepl#515]
When `tools.jar` is loaded unconditionally it can lead to problems like #463.

@bbatsov, I think we can file this as a low-hanging fruit and perhaps someone contributes a fix :).

**Comment by bbatsov** [comment]
How can we load this conditionally? I thought if you're using the JDK this gets loaded by default or something. Haven't done Java in such a long time that I don't recall very well what was the deal with it.

**Comment by alexander-yakushev** [comment]
I found how it happens here https://github.com/clojure-emacs/orchard/blob/8070ac694fc2f14343ba6c8737e7e48f901d0a7f/src/orchard/classloader.clj#L24 but that's only for Boot. I don't understand yet where cider-nrepl gets its `tools.jar` from – but it's not loaded by default by JVM, it's an opt-in local dependency.

**Comment by bbatsov** [comment]
I guess that's the other problematic code https://github.com/clojure-emacs/orchard/blob/3934ea63117b3cd3f1b459e66ada05ac173a1fc1/src/orchard/java.clj#L61

So, we should just add some check to see if it's on the classpath, before adding it right? Maybe we can just make our `add-classpath` function a bit smarter to prevent such collisions in general?

**Comment by alexander-yakushev** [comment]
Right, that's the one.

I think it should be enough to check if one of the most stable `tools.jar` classes can be resolved. Or, like you suggest, we can check for the name of the JAR on classpath, however that has a higher chance to backfire.

Regarding the generic solution for `add-classpath`, I'd probably defer that. There might be legitimate usecases when you want to add an existing (or similar) JAR to the classpath, e.g. to load a dependency  with a newer version. I'd stick to just `tools.jar` for now.

**Comment by bbatsov** [comment]
Note to self - tools.jar was removed in Java 9 (https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-D867DCCC-CEB5-4AFA-9D11-9C62B7A3FAB1)

**Comment by bbatsov** [comment]
Btw, I'll also ping @jeffvalk here to see what he think about both points. I imagine now we need something different to replace `tools.jar`, but I'm not sure what is it.

**Comment by bbatsov** [comment]
@jeffvalk Is this still relevant in light of the recent changes in Orchard?

**Comment by jeffvalk** [comment]
It's relevant as long as Java 8 support is. Also now fixed in a way that's compatible with Java 9+.
