### ISSUE TITLE
Extended selector support

### ISSUE THREAD

**Issue by SevereOverfl0w** [clojure-emacs/cider-nrepl#521]
Compared with https://github.com/cognitect-labs/test-runner our selector support is basic. It would be great to support:

- multiple inclusions
- exclusions
- multiple exclusions

Matching the behaviour of test-runner is probably wise.

**Comment by bbatsov** [comment]
Yeah, that's a great idea and it'd be super easy to achieve. The current inclusion api has to be tweaked to get a list of selectors, instead of just one and we can just replicate the same logic for the exclusions. 

A note from `test-runner` that's of relevance for us as well:

> If both inclusions and exclusions are present, exclusions take priority over inclusions.

**Comment by SevereOverfl0w** [comment]
I've started on this, and have something in a good state already. The code is lightly modified from test-runner.

I expect to PR it in the next 24 hours.
