### ISSUE TITLE
Apropos creates useless regex when not passed a `search`

### ISSUE THREAD

**Issue by SevereOverfl0w** [clojure-emacs/cider-nrepl#530]
https://github.com/clojure-emacs/cider-nrepl/blob/d18a6e89fc0057a9c78531b5ddf3c35229020993/src/cider/nrepl/middleware/apropos.clj#L21-L22

If there is no `search` this will generate `(?i:null)` which doesn't match much. It should do a `when` around the `search` first.

**Comment by bbatsov** [comment]
But isn't `search` mandatory? What exactly is apropos going to do without it?

**Comment by SevereOverfl0w** [comment]
It's fully capable of working without it now, the var-query will return everything if no `search` is provided (excluding other filters such as metadata and test). For example, you should be able to use apropos to filter for all tests by using:

```
{:op "apropos" :var-query {"test?" 1}}
```

Not providing search is the same as having search set to `#".*"`, but without the effort of actually running regex.

**Comment by MalloZup** [comment]
autogenerated with https://github.com/MalloZup/doghub:  issue inactive since 450 days. Please update the issue or close it

**Comment by bbatsov** [comment]
Fixed by #666. The PR of the Beast! 😆
