### ISSUE TITLE
Version Reporting Broken

### ISSUE THREAD

**Issue by WebsterWing** [clojure-emacs/cider-nrepl#531]
## Expected behavior
Emacs Cider receives the correct version of cider-nrepl when connecting.
## Actual behavior
Emacs sees cider-nrepl as version 1.0.0
## Steps to reproduce the problem
M-x cider-jack-in In emacs
This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.

## Environment & Version information
Emacs cider cider-20180519.1130
### cider-nrepl version

0.18.0-SNAPSHOT
cider-nrepl-0.18.0-20180520.070241-7 (I think. This is the most recent version in my .m2 folder)

### Java version

openjdk version "1.8.0_171"

### Operating system

Fedora Linux 28

**Comment by WebsterWing** [comment]
I suspect that the problem is over here instead of in emacs because the problem is very recent and there have been commits in the version related code. I may be wrong.

**Comment by bbatsov** [comment]
I've reverted the problematic change yesterday.

**Comment by bbatsov** [comment]
Infrequently. 😉
