### ISSUE TITLE
stacktrace.clj: defrecord-backed clojure code not recognised as belonging to the project

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider-nrepl#547]
## The problem

The highlighted line, which corresponds to Clojure code backed by defrecord (`(defrecord Logic ...`), should have the `'project` flag, but it doesn't.

Regular Clojure belonging to my project is correctly flagged as such.

![image](https://user-images.githubusercontent.com/1162994/46253517-dea34c00-c47d-11e8-9234-1e83a72dd1de.png)

## Debug info

* `cider.nrepl.middleware.stacktrace/ns-common-prefix` evaluates to `{:valid false, :common :missing}`
* I use `cider/cider-nrepl "0.16.0"` (for reasons), but I see the code hasn't changed in over a year.

## Workaround

`(alter-var-root #'cider.nrepl.middleware.stacktrace/ns-common-prefix (constantly {:valid true :common "app."}))`

**Comment by dpsutton** [comment]
If its saying its `:missing` then it sounds like there is no common beginning of all namespaces.

When i wrote this, it was based on an assumption that there was a common root to all namespaces that would be able to identity project namespace versus dependency namespace. Is this assumption violated in your project?

**Comment by vemv** [comment]
Thanks for the support. Good question!

Yes, we have `app*` and `unit.` roots (for sources and tests respectively).

In my described workaround I chose `app.` since chances are that the problem will be in the sources.

**Comment by vemv** [comment]
Additionally, I see `file` is `"logic.clj"` (instead of a full path), which presumably will cause https://github.com/clojure-emacs/cider/blob/15548cc3b82f2056925ace1e8edd7c35a61d1e65/cider-stacktrace.el#L567 to jump to the wrong file.

Only happens on lines corresponding to defrecord-related code.

**Comment by bbatsov** [comment]
I wonder if this is not related to https://dev.clojure.org/jira/browse/CLJ-1550
