### ISSUE TITLE
Should ns-vars-with-meta-clj return public vars?

### ISSUE THREAD

**Issue by liquidz** [clojure-emacs/cider-nrepl#566]
## Question
*  `ns-vars-with-meta-clj` uses `ns-interns` and returns all vars including private vars
   * Should `ns-vars-with-meta-clj` use `ns-publics` ?

## Actual behavior
* `ns-vars-clj` uses `ns-publics`
  * https://github.com/clojure-emacs/cider-nrepl/blob/b13881e18eb332619f2c87c5a6d6637f28442c77/src/cider/nrepl/middleware/ns.clj#L20
* `ns-vars-cljs` uses `cljs-analysis/public-vars`
  * https://github.com/clojure-emacs/cider-nrepl/blob/b13881e18eb332619f2c87c5a6d6637f28442c77/src/cider/nrepl/middleware/ns.clj#L40
* `ns-vars-with-meta-cljs` uses `cljs-analysis/public-var`
  * https://github.com/clojure-emacs/cider-nrepl/blob/b13881e18eb332619f2c87c5a6d6637f28442c77/src/cider/nrepl/middleware/ns.clj#L47
* but `ns-vars-with-meta-clj` uses `ns-interns`
  * https://github.com/clojure-emacs/cider-nrepl/blob/b13881e18eb332619f2c87c5a6d6637f28442c77/src/cider/nrepl/middleware/ns.clj#L27

### cider-nrepl version

0.18.0

**Comment by bbatsov** [comment]
@liquidz Nice catch! 

I think that was probably just an oversight and we should be consistent everywhere (meaning return public vars only).

I guess potentially we can extend this API by making it possible to request all vars, including the private ones. Does this make sense?

**Comment by liquidz** [comment]
> I guess potentially we can extend this API by making it possible to request all vars, including the private ones. Does this make sense?
@bbatsov Yes, I think too.
I'll fix codes!
