### ISSUE TITLE
allow cider and clojupyter work together

### ISSUE THREAD

**Issue by behrica** [clojure-emacs/cider-nrepl#572]
It would be great if cider could work side-by-side with clojupyter,
the clojure kernel for jupyter.

I saw that clojupyter starts an nrepl server, but cider cannot connect to it.
I tweeked a bit thw clojupyter code to set a fix nrepl port, and indeed I can then connect to it from a normal repl.
But the output looks a bit different then usualy:

```
Connecting to nREPL at 127.0.0.1:55555
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
OpenJDK 64-Bit Server VM 1.8.0_192-b26
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> [1 2 3 4 5]
{"text/plain":"[1 2 3 4 5]"}
```

in cider I see this when I connect to the mrepl port of clojupyter:

```
[nREPL] Establishing direct connection to localhost:55555 ...
[nREPL] Direct connection to localhost:55555 established
helm-M-x: Not an nREPL dict object: {
```

and indeed the message look like this:

```
(-->
  id                       "4"
  op                       "eval"
  session                  "12a250c8-0332-47c6-bbb4-24f93b9ddb1a"
  time-stamp               "2018-12-05 22:48:11.275680746"
  code                     "(str *ns*)"
  inhibit-cider-middleware "true"
)
(<--
  id         "4"
  session    "12a250c8-0332-47c6-bbb4-24f93b9ddb1a"
  time-stamp "2018-12-05 22:48:11.281413078"
  ns         "user"
  value      "{\"text/plain\":\"\\\"user\\\"\"}"
)
```

and probably cider does not understand this.

I am not sure, if it can be made working easely,
but it would be great, if I could use clojure based jupyter notebooks and cider together,
both connecting to the same nrepl server.

**Comment by behrica** [comment]
It is quite easy to see what clojupyter does:

I adds a nrepl middleware which add the mime-type to eacg response, which makes it incompatibe with cider.

There was a question on  clojupyter side as well to connect clojupyter to an other nrepl (instead of starting its own)

https://github.com/clojupyter/clojupyter/issues/60

**Comment by bbatsov** [comment]
> I adds a nrepl middleware which add the mime-type to each response, which makes it incompatibe with cider.

Where's that middleware?

> There was a question on clojupyter side as well to connect clojupyter to an other nrepl (instead of starting its own)

I'll take a look when I can.

**Comment by bbatsov** [comment]
>   value      "{\"text/plain\":\"\\\"user\\\"\"}"

Yeah, that's the problem. They shouldn't be messing with the `value` slot directly. It would have been a better idea for their middleware to insert it's metadata somewhere else.

As you can see cider-nrepl also has such middleware https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/content_type.clj, but it doesn't modify `:value` directly, as this would break normal clients. Perhaps the people behind clojupyter can adopt a similar approach?

**Comment by behrica** [comment]
This has been solved in the latest clojupyter on master:
https://github.com/clojupyter/clojupyter/pull/79

Works very nicely already. Cider and clojupter are sharing to the same nrepl process.
Allows workflows just as:

- write code in Cider and  move or copy/paste to clojupyter when done
- write some code in a clj file in Cider, which is require'd and used by clojupyter notebook
