### ISSUE TITLE
Clojure 1.10 has been released and 0.18.0 has this problem.

### ISSUE THREAD

**Issue by jconti** [clojure-emacs/cider-nrepl#579]
Clojure 1.10 has been released and 0.18.0 has this problem.

_Originally posted by @jconti in https://github.com/clojure-emacs/cider-nrepl/issues/549#issuecomment-448416580_

**Comment by jconti** [comment]
I was wondering if we could get this pull request into a 0.18.1.  Not having working error messages in cider with 1.10 is a pain, especially to new users.

**Comment by bbatsov** [comment]
I hope to release 0.19 in a few days, so a 0.18.1 will probably not be necessary.

**Comment by bbatsov** [comment]
https://github.com/clojure-emacs/cider/releases/tag/v0.19.0
