### ISSUE TITLE
Update the test middleware for nREPL 0.6

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider-nrepl#581]
nREPL 0.6 features a simplified and more robust evaluation model (see https://github.com/nrepl/nrepl/pull/98), but this break the current implementation of the test middleware, which was making some assumptions about the internals of the eval middleware. 

This ticket is a reminder to address this before nREPL 0.6 is released.

@jeffvalk would you like to tackle this? The updates should be pretty simple - seems to me that only the `with-interruptible-eval` macro should be updated.

**Comment by jeffvalk** [comment]
@bbatsov I'm not sure how soon I'd be able to get to this -- particularly if it's a research item.

**Comment by bbatsov** [comment]
I think it's just a matter of changing the use of `queue-eval` to the new `exec` as @cgrand did in the PR where he reworked the eval thread management.
