### ISSUE TITLE
Push info-java and co. down in the orchard and adapt to orchard #37

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/cider-nrepl#591]
Hi all!

This is not really a bug but just a place to open a small discussion around the new `cider-nrepl` `info` op.

In my head, thanks to https://github.com/clojure-emacs/orchard/pull/37, the only piece of logic that we would need to do in the info middleware is building the map that then goes to `orchard.info/info`.

So I am already tweaking things so that all the calls to `info-java` and `see-also` will be done in `orchard` rather then here - at the end of the day the complete `info` function should provide the full info return map. Same reasoning for the `(u/boot-project?)` logic.

I am going to work on this next so that we can at some point have feature parity for `info` in both `:clj` and `:cljs`.

### cider-nrepl version
*0.20.0*

**Comment by bbatsov** [comment]
I think we already did this.
