### ISSUE TITLE
Breaking change of nrepl.middleware.pr-values to nrepl.middleware.print in nRepl 0.6.0

### ISSUE THREAD

**Issue by danieroux** [clojure-emacs/cider-nrepl#593]
`Existing middleware descriptors whose :requires set contains
#'pr-values should instead use #'wrap-print` according to https://github.com/nrepl/nrepl/releases/tag/0.6.0

And cider-nrepl is not using wrap-print yet: https://github.com/clojure-emacs/cider-nrepl/blob/d9be18eb23ec0f807681ce051a5823a40f43af28/src/cider/nrepl.clj#L9

So bumping nRepl to 0.6.0 breaks my cider-nrepl.

**Comment by danieroux** [comment]
Fixed by open pull request https://github.com/clojure-emacs/cider-nrepl/pull/590

**Comment by cichli** [comment]
Thanks – I've released [0.21.0](https://github.com/clojure-emacs/cider-nrepl/releases/tag/v0.21.0) now, which supports nREPL 0.6.0. Client release will follow once clojure-emacs/cider#2579 is merged.
