### ISSUE TITLE
pretty-printing cider-pprint-eval-last-sexp no longer working

### ISSUE THREAD

**Issue by aiba** [clojure-emacs/cider-nrepl#595]
Running `cider-pprint-eval-last-sexp` used to pretty-print the results in the `*cider-result*` buffer.  As of upgrading to cider-nrepl 0.21.0, it no longer pretty prints.  Instead, the result prints on a 1 line (as if it were printed with `pr-str` rather than `pprint`).

## Steps to reproduce the problem

Run `cider-pprint-eval-last-sexp` on a large data structure.

## Environment & Version information

```
cider-nrepl 0.21.0
GNU Emacs 26.1
cider-emacs 0.21.0snapshot (package: 20190125.1339)
openjdk version "11.0.2" 2019-01-15
macos 10.14.3
```

**Comment by cichli** [comment]
I think you need to update your client to `20190212.1312`.

**Comment by aiba** [comment]
That worked!  Thank you.
