### ISSUE TITLE
Pretty printer zprint seem to slowdown REPL startup

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/cider-nrepl#607]
## Expected behavior

The REPL prompt should appear quite quickly.

## Actual behavior

At the beginning I though it was a problem of my custom middleware while trying the `orchard` patch.

Then I tried to back to tag `v0.21.0` and it seems like the REPL has become slower.

The prompt takes noticeably more time to appear for both Clojure and ClojureScript connections.

## Steps to reproduce the problem

Checkout `master` vs `v0.21.0` and try to start a REPL.

## Environment & Version information

Complete command that `cider` executes:

```
clojure -R:zprint -Sdeps '{:deps {nrepl {:mvn/version "0.6.0"} cider/cider-nrepl {:mvn/version "0.22.0-SNAPSHOT"}}}' -m nrepl.cmdline --middleware '["cider.nrepl/cider-middleware"]'...
```

vs

```
clojure -R:zprint -Sdeps '{:deps {nrepl {:mvn/version "0.6.0"} cider/cider-nrepl {:mvn/version "0.21.0"}}}' -m nrepl.cmdline --middleware '["cider.nrepl/cider-middleware"]'...
```

I tried:
 - `org.clojure/clojure {:mvn/version "1.9.0"}` 
 - `org.clojure/clojure {:mvn/version "1.10.0"}` 
 - `org.clojure/clojure {:mvn/version "1.10.1-beta1"}`

Just to make sure.

### cider-nrepl version

latest `master` - sorry I haven't been able to `bisect` yet

### Java version

```
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

### Operating system

Linux - Ubuntu 18.04

**Comment by arichiardi** [comment]
I think I found out that remove `-R:zprint` brings back things to normal.

I don't know if worth pinging @kkinnear - it might be what is see is the normal time it takes to load `zprint`.

**Comment by bbatsov** [comment]
I don't think there's much we can do about this, so I'll just close this.
