### ISSUE TITLE
Where does cider-nrepl finish and orchard begin

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/cider-nrepl#623]
Dear all,

I wanted to open this issue to discuss and understand myself what are the thoughts on where the line between `cider-nrepl` and `orchard` is.

I will start with an example, I have recently move the function helpers for the `resource` op to `orchard` and this is the current situation:

```clj
;; orchard/resource.clj
;;
;; ... other public functions...
(defn resource-path
  "Return the resource path for the given name."
  {:added "0.5.0"}
  [name]
  ...)

(defn resource-maps
  "Return a seq of resource maps:

    {:file    \"the absolute path to the resource\"
     :relpath \"the path of the resource relative to the classpath\"}

  If the project does not contain resources, it returns nil."
  {:added "0.5.0"}
  ...)
```

```clj
;; cider/nrepl/middleware/resource.clj

(defn handle-resource [handler msg]
  (with-safe-transport handler msg
    "resource" {:resource-path (resource/resource-path (:name msg))}
    "resources-list" {:resources-list (u/transform-value (resource/resource-maps))}))
```

Two things to notice: the `msg` is deconstructed and the `orchard` does not return exactly the data that the op needs (we need to wrap in `:resources-list` for instance).

While this seems like a good setup - `orchard` does not know about nrepl ops - I think there is something missing.

Backtracking maybe the question is more like what is the goal of `orchard`? 

In my head it would've been cool if orchard could be a library that in some way reflected the `cider-nrepl` API but only "talking data" if that makes sense.
If I were to develop an `nrepl` server today, say in ClojureScript, I would have a much easier life if I could just use the `orchard` namespaces and wrap them in whatever transport/encoding I wanted.

So what's missing? Is it another kind of library that takes the `orchard` and organized the functions as 1-to-1 mapping with the `nrepl` ops?

Kind of talking my brain out loud here, but any feedback/push back is greatly useful for this kind of design decisions.

Thanks for reading!

**Comment by SevereOverfl0w** [comment]
One goal of orchard is to support socket repl tooling, so I would say that no, orchard does not know about nrepl ops.

**Comment by bbatsov** [comment]
Indeed. IMO the API should be generic enough that the data returned is useful directly in its raw form. Clients (e.g. cider-nrepl) can always chose to massage the data to fit their needs. As our primary target are editor clients most functions should operate on a combination of a symbol + ns, but they should probably have an arity that takes a var as well, in case someone is using the API programatically. I'm not quite sure about the arities that are worth supporting. 

Right the API is suboptimal in some parts because it was lifted straight from cider-nrepl and doesn't return as rich data as it could have potentially returned. That's going to be an important point for improvements in the next couple of releases.

**Comment by arichiardi** [comment]
Agree agree that it should not know in principal but I think that it would be easier if the public api, or better "some" public api, would in a way know.

In other words I would not like for the person implementing the socket REPL to go and have a look at what cider-nrepl's return maps are. Ideally she would just require something that already knows that the resource list is represented as `{:resources-list ...}`.

I don't know if I am going anywhere with this or just overthinking it 😃 in both cases thank you for the prompt replies!

**Comment by bbatsov** [comment]
> In other words I would not like for the person implementing the socket REPL to go and have a look at what cider-nrepl's return maps are. Ideally she would just require something that already knows that the resource list is represented as {:resources-list ...}.

Isn't this what API docs are all about? ;-) If we have designed a reasonable API (and documented it well) in Orchard then no client will ever have to consult cider-nrepl. On a related note - at some point we'll have to revisit the documentation of cider-nrepl itself, as it should be easier to figure out how to use the existing ops.

**Comment by bbatsov** [comment]
Btw, these days we finally have cider-nrepl documented reasonably well https://docs.cider.mx/cider-nrepl/index.html Orchard's up next.
