### ISSUE TITLE
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Error building classpath. Don't know how to create ISeq from: clojure.lang.Symbol

### ISSUE THREAD

**Issue by wilsonalmeida** [clojure-emacs/cider-nrepl#627]
## Expected behavior
Running cider-jack-in should launch a REPL
## Actual behavior
Get the an error :
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Error building classpath. Don't know how to create ISeq from: clojure.lang.Symbol

## Steps to reproduce the problem
1) create a deps.edn file
2) run cider-jack-in

When I run the same command on the command line it works.

## Environment & Version information

emacs 26.1 (Build 1, x86_64-w64-mingw32)

### cider-nrepl version
0.21.0

### Java version
1.8

### Operating system
Windows 10

Here's the deps.edn file..nothing unusual here
{:paths ["src/clj" "src/cljs" "resources"]

 :deps { org.clojure/clojure {:mvn/version "1.10.0"}
        metosin/reitit {:mvn/version "0.3.7"}
        ring {:mvn/version "1.7.1"}
        migratus {:mvn/version "1.2.3"}
        com.h2database/h2 {:mvn/version "1.4.199"}
        org.postgresql/postgresql {:mvn/version "42.2.5"}
        org.clojure/java.jdbc {:mvn/version "0.7.9"}
        cumulus {:mvn/version "0.1.2"}
        com.layerware/hugsql {:mvn/version "0.4.9"}
        selmer {:mvn/version "1.12.12"}
        ring-webjars {:mvn/version "0.2.0"}
        ring/ring-defaults {:mvn/version "0.3.2"}
        ring/ring-anti-forgery {:mvn/version "1.3.0"}
        luminus/ring-ttl-session {:mvn/version "0.3.3"}
        hiccup {:mvn/version "1.0.5"}
        org.clojure/clojurescript {:mvn/version "1.10.520"}
        reagent {:mvn/version "0.8.1"}
        cljs-ajax {:mvn/version "0.8.0"}
        cljs-http {:mvn/version "0.1.46"}
        org.webjars.npm/bulma {:mvn/version "0.7.4"}
        org.webjars/font-awesome {:mvn/version "5.3.1"}
        com.cognitect/transit-cljs {:mvn/version "0.8.256"}
        com.cognitect/transit-clj {:mvn/version "0.8.313"}
        metosin/muuntaja {:mvn/version "0.6.4"}
        metosin/jsonista {:mvn/version "0.2.3"}
        com.andrewmcveigh/cljs-time {:mvn/version "0.5.2"}
        }
 :aliases {:run {:main-opts ["-m" "reitit-with-database.server"]}
           :cljsbuild
           { :main-opts
            ["-m" "cljs.main" "-co" "cljsbuild.edn" "-c"]}
           }
 }

**Comment by bbatsov** [comment]
It'd be useful if you could share the command-line string that was generated by `cider-jack-in`.

**Comment by wilsonalmeida** [comment]
Hi Bozhidar,

I've created another project with nothing much except a `deps.edn` file and a `clore.clj`.
Calling `cider-jack-in` results in the same error..  Here's the emacs message output 

```
[nREPL] Starting server via "c:/Users/wilson.DARA/AppData/Local/Programs/clojure/bin/clojure.exe" -Sdeps '{:deps {nrepl {:mvn/version ""0.6.0""} refactor-nrepl {:mvn/version ""2.5.0-SNAPSHOT""} cider/cider-nrepl {:mvn/version ""0.21.1""}}}' -m nrepl.cmdline --middleware '["refactor-nrepl.middleware/wrap-refactor", "cider.nrepl/cider-middleware"]'...
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Error building classpath. Don't know how to create ISeq from: clojure.lang.Symbol

java.lang.IllegalArgumentException: Don't know how to create ISeq from: clojure.lang.Symbol
```

**Comment by bbatsov** [comment]
Ah, it seems you're on Windows. I'm assuming that the command string there doesn't work properly - from what I know there were some issues with `tools.deps` and Windows. The latest version of CIDER has some workaround for this that relies on Powershell, so you might check it out. See https://github.com/scottdw/cider/commit/cf0426a2390c82351f8b14b88645047f002479ce

**Comment by wilsonalmeida** [comment]
Hi Bozhidar,

Just to test it out, I manually applied the changes to my local `cider.el` and byte compiled the file, set the `cider-clojure-cli-command` to `powershell`.  Now it starts it via `powershell` ...all gibberish as it's encoded, but I still get an error.

```
[nREPL] Starting server via "c:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" -encodedCommand YwBsAG8AagB1AHIAZQAgAC0AUwBkAGUAcABzACAAJwB7ADoAZABlAHAAcwAgAHsAbgByAGUAcABsACAAewA6AG0AdgBuAC8AdgBlAHIAcwBpAG8AbgAgACIAIgAiACIAMAAuADYALgAwACIAIgAiACIAfQAgAHIAZQBmAGEAYwB0AG8AcgAtAG4AcgBlAHAAbAAgAHsAOgBtAHYAbgAvAHYAZQByAHMAaQBvAG4AIAAiACIAIgAiADIALgA1AC4AMAAtAFMATgBBAFAAUwBIAE8AVAAiACIAIgAiAH0AIABjAGkAZABlAHIALwBjAGkAZABlAHIALQBuAHIAZQBwAGwAIAB7ADoAbQB2AG4ALwB2AGUAcgBzAGkAbwBuACAAIgAiACIAIgAwAC4AMgAxAC4AMQAiACIAIgAiAH0AfQB9ACcAIAAtAG0AIABuAHIAZQBwAGwALgBjAG0AZABsAGkAbgBlACAALQAtAG0AaQBkAGQAbABlAHcAYQByAGUAIAAnAFsAIgAiAHIAZQBmAGEAYwB0AG8AcgAtAG4AcgBlAHAAbAAuAG0AaQBkAGQAbABlAHcAYQByAGUALwB3AHIAYQBwAC0AcgBlAGYAYQBjAHQAbwByACIAIgAsACAAIgAiAGMAaQBkAGUAcgAuAG4AcgBlAHAAbAAvAGMAaQBkAGUAcgAtAG0AaQBkAGQAbABlAHcAYQByAGUAIgAiAF0AJwA=...
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Execution error at nrepl.cmdline/parse-cli-values$fn (cmdline.clj:248).

EOF while reading string
Full report at:

C:\Users\WILSON~1.DAR\AppData\Local\Temp\clojure-6045767427534102360.edn
```
I am not really a windows person. I use Linux at home and I've my setup working perfectly there.  I was just trying to utilise free time at work by setting up a Clojure development environment to try out a few things.  I can't install Linux here due to work policies :(.  For now, I'm happy to run the  `REPL` from the command line and connect to it from `emacs` using `cider-connect`.  

Thanks for you help 👍

**Comment by bbatsov** [comment]
@scottdw Can you help with debugging this?

**Comment by scottdw** [comment]
The encoded command in https://github.com/clojure-emacs/cider-nrepl/issues/627#issuecomment-534316473 appears to be double escaping the `-Sdeps` argument (the `--middleware` argument seems fine though). To view the decoded command evaluate the following elisp snippet in the `*scratch*` buffer (replacing the base64-string as needed).

```elisp
(insert (decode-coding-string (base64-decode-string "YwBsAG8AagB1AHIAZQAgAC0AUwBkAGUAcABzACAAJwB7ADoAZABlAHAAcwAgAHsAbgByAGUAcABsACAAewA6AG0AdgBuAC8AdgBlAHIAcwBpAG8AbgAgACIAIgAiACIAMAAuADYALgAwACIAIgAiACIAfQAgAHIAZQBmAGEAYwB0AG8AcgAtAG4AcgBlAHAAbAAgAHsAOgBtAHYAbgAvAHYAZQByAHMAaQBvAG4AIAAiACIAIgAiADIALgA1AC4AMAAtAFMATgBBAFAAUwBIAE8AVAAiACIAIgAiAH0AIABjAGkAZABlAHIALwBjAGkAZABlAHIALQBuAHIAZQBwAGwAIAB7ADoAbQB2AG4ALwB2AGUAcgBzAGkAbwBuACAAIgAiACIAIgAwAC4AMgAxAC4AMQAiACIAIgAiAH0AfQB9ACcAIAAtAG0AIABuAHIAZQBwAGwALgBjAG0AZABsAGkAbgBlACAALQAtAG0AaQBkAGQAbABlAHcAYQByAGUAIAAnAFsAIgAiAHIAZQBmAGEAYwB0AG8AcgAtAG4AcgBlAHAAbAAuAG0AaQBkAGQAbABlAHcAYQByAGUALwB3AHIAYQBwAC0AcgBlAGYAYQBjAHQAbwByACIAIgAsACAAIgAiAGMAaQBkAGUAcgAuAG4AcgBlAHAAbAAvAGMAaQBkAGUAcgAtAG0AaQBkAGQAbABlAHcAYQByAGUAIgAiAF0AJwA=")
                      'utf-16le))
```

From comment https://github.com/clojure-emacs/cider-nrepl/issues/627#issuecomment-533930166 it looks like there is a `clojure.exe` in the path. The official `tools.deps` for windows distribution does not contain an executable (hence the need for the powershell stuff) and that executable may be being used instead of the powershell module (not sure that would actually cause problems though). Also in that comment the `-Sdeps` string is escaped with double double-quotes while the `--middleware` argument is not.

@wilsonalmeida review your `cider.el` changes against https://github.com/clojure-emacs/cider/commit/cd68e207ffe68e7e2f39b7ca884959f627fb468d (the version that was merged in). I think the main issue here is the incorrect escaping of the `-Sdeps` and/or `--middleware` arguments. For the powershell version, when decoded, double quotes should be repeated once to escape.

**Comment by wilsonalmeida** [comment]
Thank you @scottdw  and @bbatsov .  
I remove `clojure.exe` from my path, reinstalled `tools.deps` and  `cider` package .. and now everything is hunky dory 👍 

Really appreciate all the help in debugging this issue.  Cheers 🥇

**Comment by wilsonalmeida** [comment]
Now i've a different issue..when I specify 
```
(cider-clojure-cli-global-options . "-Arepl")
``` 
in `.dir-locals.el` and invoke `clojure-jack-in`, I get the following error:
```
[nREPL] Starting server via "c:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" -encodedCommand YwBsAG8AagB1AHIAZQAgAC0AQQByAGUAcABsACAALQBTAGQAZQBwAHMAIAAnAHsAOgBkAGUAcABzACAAewBuAHIAZQBwAGwAIAB7ADoAbQB2AG4ALwB2AGUAcgBzAGkAbwBuACAAIgAiADAALgA2AC4AMAAiACIAfQAgAHIAZQBmAGEAYwB0AG8AcgAtAG4AcgBlAHAAbAAgAHsAOgBtAHYAbgAvAHYAZQByAHMAaQBvAG4AIAAiACIAMgAuADUALgAwAC0AUwBOAEEAUABTAEgATwBUACIAIgB9ACAAYwBpAGQAZQByAC8AYwBpAGQAZQByAC0AbgByAGUAcABsACAAewA6AG0AdgBuAC8AdgBlAHIAcwBpAG8AbgAgACIAIgAwAC4AMgAyAC4AMQAiACIAfQB9AH0AJwAgAC0AbQAgAG4AcgBlAHAAbAAuAGMAbQBkAGwAaQBuAGUAIAAtAC0AbQBpAGQAZABsAGUAdwBhAHIAZQAgACcAWwAiACIAcgBlAGYAYQBjAHQAbwByAC0AbgByAGUAcABsAC4AbQBpAGQAZABsAGUAdwBhAHIAZQAvAHcAcgBhAHAALQByAGUAZgBhAGMAdABvAHIAIgAiACwAIAAiACIAYwBpAGQAZQByAC4AbgByAGUAcABsAC8AYwBpAGQAZQByAC0AbQBpAGQAZABsAGUAdwBhAHIAZQAiACIAXQAnAA==
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: #< CLIXML

WARNING: Specified aliases are undeclared: [:-Sdeps]

Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (REPL:-2).

{:deps {nrepl {:mvn\version "0.6.0"} refactor-nrepl {:mvn\version "2.5.0-SNAPSHOT"} cider\cider-nrepl {:mvn\version "0.22.1"}}} (The system cannot find the path specified)
```
I followed @scottdw  suggestion to decode the encoded command and this is what I get
```
"clojure -Arepl -Sdeps '{:deps {nrepl {:mvn/version \"\"0.6.0\"\"} refactor-nrepl {:mvn/version \"\"2.5.0-SNAPSHOT\"\"} cider/cider-nrepl {:mvn/version \"\"0.22.1\"\"}}}' -m nrepl.cmdline --middleware '[\"\"refactor-nrepl.middleware/wrap-refactor\"\", \"\"cider.nrepl/cider-middleware\"\"]'"
```

**Comment by wilsonalmeida** [comment]
Sorry for the trouble...i figured out the reason for the error message : 
I was using `-Arepl` instead of `-A:repl`.  Strangely, it worked earlier when I was not using `powershell` module and using `clj` instead.   Closing this.
