### ISSUE TITLE
Integrating ClojureScript completions from compliment

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/cider-nrepl#634]
This issue describes how to integrate https://github.com/alexander-yakushev/compliment/pull/62 in `cider-nrepl`.

The new namespace is [`compliment.sources.cljs`](https://github.com/alexander-yakushev/compliment/blob/d94312c4719381ef5d6459ee8429d18174754c22/src/compliment/sources/cljs.cljc) and contains the classic `candidates` function for providing completions.

The only new thing to do is to set the dynamic var [`*compiler-env*`](https://github.com/alexander-yakushev/compliment/blob/d94312c4719381ef5d6459ee8429d18174754c22/src/compliment/sources/cljs.cljc#L267) containing the ClojureScript env map.

Needless to say that the two completions methods are (for now, but I have a plan) mutually exclusive, therefore we also need an `if` in case the ClojureScript env is there.

After integrating, the `cljs-tooling` library can cease to exist and can be removed from the dependencies ⚔️ 😀

**Comment by arichiardi** [comment]
I am working on a branch and I think something else is necessary, will push that branch.

**Comment by arichiardi** [comment]
Actually the approach is kind of different. Had to recheck cause it has been a while.

The function to call in both cases is [`compliment. core/completions`](https://github.com/alexander-yakushev/compliment/blob/master/src/compliment/core.clj#L54) but in case of a Cljs environment we need to pass an option-map containing the `:sources` key set to the right keyword. 

The problem is that we had not decided at the time neither the keyword nor if the mechanism was correct so I need another patch to `compliment` before proceeding.

**Comment by bbatsov** [comment]
The cljs completion code eventually ended up in https://github.com/rksm/clj-suitable
