### ISSUE TITLE
Could not find artifact cider:cider-nrepl:jar:0.22.1 in clojars (https://repo.clojars.org/)

### ISSUE THREAD

**Issue by DevinKin** [clojure-emacs/cider-nrepl#645]
## Actual behavior
After I installed Spacemacs, I tried to use the cider-jack-in command, but found the following error.
![image](https://user-images.githubusercontent.com/30171168/64118396-2804c580-cdca-11e9-8db4-c986233a8aeb.png)

## Steps to solve this problem
I heard there was a problem pushing clojars, which will be fixed in a few days, thanks to the maintainers who worked hard on the project. If you are in the same situation as me, you can use the following solution.

set the variable `cider-required-middleware-version` as following value
![image](https://user-images.githubusercontent.com/30171168/64119490-93e82d80-cdcc-11e9-9bd0-15a9fbd9cf79.png)

**Comment by bbatsov** [comment]
The clojars issue was fixed and I just uploaded the missing `cider-nrepl` release. Sorry about this mess!
