### ISSUE TITLE
Duplicate dependencies and middlewares w/lein-modules

### ISSUE THREAD

**Issue by dcarley** [clojure-emacs/cider-nrepl#673]
I'm not sure this the right project to report this in. [lein-modules](https://github.com/jcrossley3/lein-modules) isn't actively maintained. However it looks like cider-nrepl's middleware function could be more idempotent:

- https://github.com/jcrossley3/lein-modules/blob/0.3.11/src/lein_modules/inheritance.clj#L59-L63
- https://cljdoc.org/d/leiningen/leiningen/2.9.3/api/leiningen.core.project#set-profiles
- https://github.com/clojure-emacs/cider-nrepl/blob/v0.24.0/src/cider_nrepl/plugin.clj#L55-L93
- https://github.com/technomancy/leiningen/blob/master/doc/PLUGINS.md#project-middleware

It can be worked around by explicitly declaring lein-module's middleware in the project, but the behaviour is surprising if you don't:
```clojure
  :middleware [lein-modules.plugin/middleware]
```

Although not practical for injection, it's interesting to note that it also doesn't happen if the plugins are specified together in the opposite order:
```clojure
  :plugins [[cider/cider-nrepl "0.24.0"]
            [lein-modules "0.3.11"]])
```

## Expected behavior

I'd like to use a combination of:
- [lein-modules](https://github.com/jcrossley3/lein-modules)
- `:pedantic? :abort`
- cider-nrepl without injection ([documented here](https://docs.cider.mx/cider/0.24/caveats.html#_injecting_dependencies_and_leiningen_pedantic_abort_mode))

For the purposes of both:
- CIDER in Emacs
- `lein repl` from the CLI

## Actual behavior

The dependency is injected twice which triggers an abort:
```
$ lein repl
Possibly confusing dependencies found:
[cider/cider-nrepl "0.24.0"]
 overrides
[cider/cider-nrepl "0.24.0"]

Consider using these exclusions:


Aborting due to :pedantic? :abort
```

The duplicate dependency can be seen with [lein-pprint](https://github.com/technomancy/leiningen/tree/master/lein-pprint):
```
$ lein with-profile repl pprint :dependencies
([cider/cider-nrepl "0.24.0"]
 [cider/cider-nrepl "0.24.0"]
 [org.clojure/clojure "1.10.1"]
 [nrepl/nrepl "0.6.0"])
```

The middlewares are also duplicated:
```
$ lein with-profile repl pprint :repl-options | rg cider.nrepl/wrap-classpath
  cider.nrepl/wrap-classpath
  cider.nrepl/wrap-classpath
```

## Steps to reproduce the problem

`project.clj`:
```clojure
(defproject lein-modules-cider-nrepl "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.10.1"]]
  :pedantic? :abort
  :plugins [[lein-modules "0.3.11"]])
```

`profiles.clj`:
```clojure
{:repl {:dependencies [[nrepl "0.6.0"]]
        :plugins [[cider/cider-nrepl "0.24.0"]]}}
```

### cider-nrepl version

`0.24.0`

### Java version

```
$ lein version
Leiningen 2.9.3 on Java 1.8.0_172 Java HotSpot(TM) 64-Bit Server VM
```

### Operating system

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.6
BuildVersion:   17G11023
```

**Comment by vemv** [comment]
More often than not, dependency management is a consumer problem, not a library problem. We cannot control what plugins, settings etc people use.

Is there anything specific we can do to make this problem easy?

If not, I'd be inclined to close this issue.

As a recommendation, you can always set `:pedantic?` only in CI. It tends to be necessary anyway sooner or later, dev setups can get pretty hairy.
