### ISSUE TITLE
:key is missing as required param to debug-input op in docs

### ISSUE THREAD

**Issue by bpringe** [clojure-emacs/cider-nrepl#675]
I just want to point this out. I'm not sure on the details of the doc editing/generation, but it would be helpful to include this info in the docs: https://github.com/clojure-emacs/cider-nrepl/blob/958c0c13bb9bc7c369adbe8466dbdf03f34888e9/src/cider/nrepl/middleware/debug.clj#L47

**Comment by bbatsov** [comment]
Good catch!

**Comment by hodgesto** [comment]
If I were to help with this, I assume it would need more than just adding a line to doc/modules/ROOT/pages/nrepl-api/ops.adoc? Forgive me as I am very new but would really like to get involved.

**Comment by bbatsov** [comment]
You'll have to update the middleware descriptor for the debug middleware and run `lein docs` afterwards to re-gen `ops.adoc`.

**Comment by hodgiwabi** [comment]
#696 Created
