### ISSUE TITLE
Weird test failures

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider-nrepl#678]
After https://github.com/clojure-emacs/cider-nrepl/commit/ed793166f8d33a2e18939cafcc2e1951c1cc890c the build started failing in a really weird way (like ClojureScript/Piggieback's missing). I can't see any connection between disabling suitable and the failure's, though.

**Comment by bbatsov** [comment]
@arichiardi Any idea what might be causing this?

**Comment by arichiardi** [comment]
I knew suitable has some shadow-specific parts, not really in the meta/info part...it smells like the possible problem but I will definitely take a look when I have some time.

**Comment by bbatsov** [comment]
I'm just not sure those failures are even related to suitable. Anyways, any help would be welcome!

**Comment by bbatsov** [comment]
@clojure-emacs/cider Any ideas from anyone? Sorry about the ping, but I just came back to this ticket and I still can't figure out what broke everything cljs-related. It's like in the tests Piggieback doesn't run at all.

**Comment by bbatsov** [comment]
Fixed in #691. Turns out it was suitable indeed.

**Comment by vemv** [comment]
Issue good to close?

**Comment by bbatsov** [comment]
Indeed.
