### ISSUE TITLE
Completion of some Java packages/classes does not work on Windows.

### ISSUE THREAD

**Issue by peterwang** [clojure-emacs/cider-nrepl#708]
The cause of the issue is in its dependency:
`cider.nrepl.inlined-deps.compliment.v0v3v11.compliment.utils/classes-on-classpath`

It would be fixed upon the accept of the PR:
https://github.com/alexander-yakushev/compliment/pull/79

## Expected behavior
Completion of Java packages/classes should work. 
For example, when `java.util.` is typed in the REPL,
the classes inside package java.util should be listed.

## Actual behavior
When `java.util.` is typed in the REPL,
the classes inside package java.util were not listed.

## Steps to reproduce the problem
On windows, lein new <app>, 
`cider-jack-in` the project,
try the steps above.

### cider-nrepl version

cider-nrepl-0.26.0

### Java version

Java 16.0.1

### Operating system

Windows 10

**Comment by vemv** [comment]
Excellent report, thanks!

**Comment by vemv** [comment]
@peterwang: Release soon!

**Comment by peterwang** [comment]
Wow! Thanks! Can't wait to try the new release.

**Comment by vemv** [comment]
Released in `[cider/cider-nrepl "0.27.3"]`!
