### ISSUE TITLE
test-var-query does not run tests with `+` in the name

### ISSUE THREAD

**Issue by bpringe** [clojure-emacs/cider-nrepl#730]
## Expected behavior

Tests with `+` in the name are run successfully.

## Actual behavior

Tests with `+` in the name are _not_ run successfully.

## Steps to reproduce the problem

Please see this Calva issue here for details: https://github.com/BetterThanTomorrow/calva/issues/1383.

It seems that if a `+` is in the middle of the test name, the test isn't found. If the `+` is at the beginning of the test name, an exception is thrown in the repl.

In Calva, we send the test as below, and I verified that `test` has the appropriate test name - that it was not altered by Calva before being send to cider-nrepl.

```javascript
            this.client.write({
                op: "test-var-query",
                ns,
                id,
                session: this.sessionId,
                "var-query": {
                    "ns-query": {
                        exactly: [ns]
                    },
                    search: test,
                    "search-property": "name"
                }
            });
```

### cider-nrepl version

0.26.0

### Java version

```sh
openjdk 16.0.2 2021-07-20
OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7)
OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (build 16.0.2+7, mixed mode, sharing)
```

### Operating system

MacOS Monterey

**Comment by vemv** [comment]
I gave this a quick go in cider-nrepl's test suite and couldn't reproduce it: a deftest called `+foo` is run, including any side-effects.

Honestly the issue would surprise me much - cider-nrepl generally isn't heuristic-based so I'm not sure the var name isn't relevant to begin with.

@bbatsov ,  can you reproduce this in emacs CIDER?

> https://github.com/BetterThanTomorrow/calva/issues/1383

Perhaps things are being serialized funnily somewhere in the stack?

**Comment by vemv** [comment]
Mmm I was confused by the issue description which doesn't emphasize test-var-query (as opposed to test running in general), unlike the title.

Will check out again later today!

**Comment by bbatsov** [comment]
My guess is that `+` is messing up the `var-query`, but I'll have to test it explicitly. The old more specific test ops were deprecated in favor of `test-var-query`, as it provides all of their functionality and more.

**Comment by vemv** [comment]
I've tested `orchard.query/vars` which is what `test-var-query` uses and it appears to work just fine:

![image](https://user-images.githubusercontent.com/1162994/143334460-99fb4829-697e-4548-aa08-2f29edac17cd.png)

If you pass a `+` it should be escaped (presumably client-side: we shouldn't second-guess what a client meant). `Pattern/quote` can be useful, for example.

Does that make sense, @bpringe ?

**Comment by bpringe** [comment]
Ah, yes that does make sense. Thanks! I'll close this, then.
