### ISSUE TITLE
WARNING: update-vals already refers to: #'clojure.core/update-vals

### ISSUE THREAD

**Issue by kanwei** [clojure-emacs/cider-nrepl#734]
## Expected behavior

No warnings

## Actual behavior

Warnings:

```
WARNING: update-vals already refers to: #'clojure.core/update-vals in namespace: cider.nrepl.inlined-deps.orchard.v0v7v3.orchard.misc, being replaced by: #'cider.nrepl.inlined-deps.orchard.v0v7v3.orchard.misc/update-vals
```

## Steps to reproduce the problem

Use new clojure 1.11.0-alpha3

### cider-nrepl version

0.27.2

**Comment by vemv** [comment]
Hi, thanks for the report!

This was fixed in https://github.com/clojure-emacs/orchard/commit/6c9e5d973beacaeb113c49378f2db5d7415026cc and will be included in the next CIDER release, surely pretty soon.
