### ISSUE TITLE
Java classes are not available after `undef-all` and reload

### ISSUE THREAD

**Issue by danskarda** [clojure-emacs/cider-nrepl#752]
## Expected behavior

Classes which are imported by default (Long, Throwable, Exception) are available after undef-all and defining the namespace again. 

For example:

```clojure
(ns foo.bar)

inc
;; => #function[clojure.core/inc]

Long
;; => java.lang.Long
```
## Actual behavior

I `cider-undef-all` from Emacs and evaluate `ns` form. All clojure.core functinons are imported to namespace (which is correct), but java classes (Long, Throwable, Exception) are not available. This is unfortunate as `Exception` is usually used in `(catch Exception ... )` blocks etc.  

```clojure
(ns foo.bar)

inc
;; => #function[clojure.core/inc]

Long
;; => Exception unable to resolve symbol Long in this context
```

### cider-nrepl version

cider-nrepl. 0.28.3
nrepl 0.9.0
Cider 1.4.0

### Java version

```clojure
(System/getProperty "java.version")
"11.0.15"
```

### Operating system

Debian Sid

**Comment by vemv** [comment]
Thanks! Will be closed by https://github.com/clojure-emacs/cider-nrepl/pull/751

**Comment by danskarda** [comment]
Great. Thanks. I should have checked also pull requests, not only open / closed issues.
