### ISSUE TITLE
Feature idea: Timing information in test report

### ISSUE THREAD

**Issue by DerGuteMoritz** [clojure-emacs/cider-nrepl#755]
When working on optimizing test performance, it would be very handy to have timing information in the test report. Something like this:

<pre>
Tested 1 namespaces in 12666 ms
Ran 75 assertions, in 17 test functions
75 passed
</pre>

**Comment by vemv** [comment]
This sounds like a reasonable request, feel free to create a PR as elaborate (or simple) as desired.

I'm thinking different granularities should be included in the return value, e.g. per-ns, per-var, possibly more.

If a single run is for a [`var-query`](https://github.com/clojure-emacs/cider-nrepl/blob/4d79be8a3769f5b1959eebb5538ddb8242ac8bed/src/cider/nrepl/middleware/test.clj#L274) that will exercise two namespaces with two vars each, I would expect:

* the timing info for each of the 4 vars
* the timing info for each of the 2 namespaces
* the total timing info.

(quite obviously, it's up to cider.el to decide which of this info is relevant and will be presented to the user. Might be customizable)

Sounds good? Is it something you'd be willing to work on?

I'd be happy to assist with reviewing and tweaks.

Cheers - V

**Comment by DerGuteMoritz** [comment]
Thanks for the swift reply! Your thoughts make sense and sound good to me :+1: In principle I'd be willig to work on this but at the moment I can't make time for it. I'll post another update here when I get to it. If anyone else is inclined to start working on it in the meantime, be sure to also post here so that we don't end up duplicating efforts :pray:
