### ISSUE TITLE
not shown exception stacktrace in Doom Emacs

### ISSUE THREAD

**Issue by vganshin** [clojure-emacs/cider-nrepl#765]
## Expected behavior

I use doom emacs and earlier when I evaluated some expression, which threw an expection, new buffer opened with stacktrace.

## Actual behavior

With the latest cider-nrepl version (0.29.0) I can see only errors in Emacs itself. This is what I see in \*Message\* buffer.

```
error in process filter: cider--handle-stacktrace-response: Wrong type argument: sequencep, t
error in process filter: Wrong type argument: sequencep, t
```

## Steps to reproduce the problem

1. Run clojure repl with cider-nrepl 0.29.0
2. Connect to the repl with latest Doom Emacs.
3. Eval `(/ 1 0)`.

### cider-nrepl version

0.29.0

### Java version

openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)

### Operating system

macOS Ventura 13.0.1

### Emacs/Doom version

```sh
# ./doom version
GNU Emacs     v28.2            nil
Doom core     v3.0.0-pre       HEAD -> master e96624926 2023-01-01 21:55:13 -0500
Doom modules  v22.10.0-pre     HEAD -> master e96624926 2023-01-01 21:55:13 -0500
```

# Additional context

cider-nrepl0.28.7 works fine.

**Comment by ddegr** [comment]
Facing that behavior as well

**Comment by bbatsov** [comment]
What version of CIDER are using? According to the linked ticket this seems to work fine with the CIDER 1.16.

**Comment by vganshin** [comment]
@bbatsov CIDER 1.5.0.

I will check, how to update it in Doom Emacs. Thank you.

**Comment by vganshin** [comment]
> What version of CIDER are using? According to the linked ticket this seems to work fine with the CIDER 1.16.

Did you mean 1.6.0? https://stable.melpa.org/#/cider

**Comment by vganshin** [comment]
Cider 1.6.0 works fine. Thank you!
