### ISSUE TITLE
Indentation inference for defmacros

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider-nrepl#777]
(IDK if this had been talked about before)

Given an arbitrary macro that lacks `:style/indent` metadata, e.g. `(defmacro fact [& forms]`, I'd find it most practical that CIDER inferred a sensible `indent` value for it.

A sensible rule of thumb is:

> indent = <number of macro args before `&`>

For instance, `[a b & c]` has two arguments before `&`, so the inferred indent should be `2`.

There occasionally exist macros without `&`, e.g.:

```
(defmacro foo [opts body]
```

For those, we can devise a similar rule of thumb:

> indent = <number of macro args before an argument named `body`>

(or `forms`, `tail`, similar words)

So that foo would have an indent of `1`.

I understand that this is not quite 'pure' in approach. But my experience over the years is that very few people, even among CIDER users, will remember to add the metadata manually.

Ultimately, users can of course always add metadata, which would override any inference.

WDYT?

Cheers - V

**Comment by bbatsov** [comment]
Yeah, that'd be fine. That's similar to how SLIME used to work out indentation when it wasn't specified - by relying on the the names of some params (I think `body` and `forms`). In general I'm all for adding some sensible inference to simplify the lives of users.
