### ISSUE TITLE
Improve `load-file`'s output

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider-nrepl#804]
## Context

cider.el uses `"load-file"` (as defined in nREPL - not cider-nrepl!) for certain ops.

The problem being, load-file includes a rather poor `err`:

```lisp
(<--
  id         "28"
  session    "0f8dc717-0b97-4943-916b-dcb21ac7ce69"
  time-stamp "2023-08-21 18:08:40.629802000"
  err        "Execution error (ArithmeticException) at haystack.analyzer/eval1311841 (analyzer.clj:18).
Divide by zero
"
)
```

...when compared to `analyze-last-stacktrace`'s `"message"`:

```lisp
message "Syntax error macroexpanding at (/Users/vemv/haystack/src/haystack/analyzer.clj:18:1)."
```

The latter has a proper filename. `cider-jump` can only use that, else its internal parsing will return `nil` and no `jump`ing will happen.

## Proposed task

Create a piece of middleware that improves (or expands with a separate key) `load-file`'s output.

This way, consumers can remain basically unchanged, and have more useful info.

## Alternative

Leave it as-is and send a request separately to analyze-stack-trace.

The downside I see is that this would complicate the client side with an abundance of requests, which are always subject to fail, and asynchrony.

**Comment by vemv** [comment]
if response contains err and matches

  "Execution error (ArithmeticException) at
nrepl.load-file.compile-time-exception/eval3644
(load_file/compile_time_exception.clj:4).\nDivide by zero\n",

replace nrepl.load-file.compile-time-exception/eval3644

such that we obtain
/Users/vemv/proj/src/nrepl/load_file/compile_time_exception.clj

i.e.

absolutize
replace - -> _
remove eval123
add .clj
check file exists

**Comment by bbatsov** [comment]
Shouldn't this be changed in nREPL? I doubt people are parsing this message, given that the file information is coming from elsewhere.

**Comment by vemv** [comment]
I gave it a shot yesterday in nREPL, and it seemed excessively complicated to accomplish. The `:err` is computed by `replying-PrintWriter`. We don't want to inspect every piece that its streamed to stderr just for a particular use case.

At this point I'm doubting whether it's feasible in cider-nrepl! (Although I'll give it a try)

And changing things cider.el side would seem more reasonable to me than yesterday.

**Comment by vemv** [comment]
Finally I'll do this cider.el side.
