### ISSUE TITLE
nrepl fails with "No such namespace: orchard.java.parser-utils"

### ISSUE THREAD

**Issue by rfb** [clojure-emacs/cider-nrepl#857]
## Expected behavior

cider-nrepl should start using alias from tools.deps

## Actual behavior

fails with `No such namespace: orchard.java.parser-utils`

```
rfb@snass ~/projects/test-project$ clj -M:cider
Execution error (IllegalArgumentException) at orchard.misc/require-and-resolve (misc.clj:161).
No such namespace: orchard.java.parser-utils

Full report at:
/tmp/clojure-12834814114944848857.edn
```

## Steps to reproduce the problem

empty directory with deps.edn:

```
{:deps    {org.clojure/clojure {:mvn/version "1.11.1"}}
 :aliases {:cider {:extra-deps {cider/cider-nrepl {:mvn/version "0.47.1"}}
                   :main-opts  ["-m" "nrepl.cmdline" "--middleware" "[cider.nrepl/cider-middleware]" "-i"]}}}
```

### cider-nrepl version

0.47.1

### Java version

```
rfb@snass ~/projects/test-project$ java --version
openjdk 21 2023-09-19
OpenJDK Runtime Environment (build 21+-adhoc.nixbld.source)
OpenJDK 64-Bit Server VM (build 21+-adhoc.nixbld.source, mixed mode, sharing)
```

### Operating system

Guix System

**Comment by vemv** [comment]
This is a well-known one - Guix users (just like most Linux users) should ensure their JDK is a full one.

We have guix-specific instructions at https://docs.cider.mx/cider/troubleshooting.html

Cheers - V

**Comment by rfb** [comment]
Oh! Thank you!
