### ISSUE TITLE
The debugger returns the wrong `coor` for atoms

### ISSUE THREAD

**Issue by PEZ** [clojure-emacs/cider-nrepl#865]
The debug response coordinates for the dereferenced atom contains an extra `1`, throwing the client out of whack. For the repro code below the `coor` is returned as `[3 1]`,  where it probably should just be `[3]`. At least that would make Calva happy. 

A minimal repro project: https://github.com/PEZ/cider-nrepl-debugger-issues, thanks @javierrweiss!

Issue reported on Calva:
* https://github.com/BetterThanTomorrow/calva/issues/2501

## Steps to reproduce the problem

In CIDER or Calva:

1. Evaluate the top level forms here:
    ```clojure
    (def !a (atom 0))
    
    #dbg
    (defn boom
      []
      @!a)
    
    (comment
      (boom)
      )
    ```
1. Evaluate `(boom)`

## Expected behavior

The debugger should stop showing the value 0 from the `@!a` expression.

## Actual behavior

Things go BOOM. A bit different symptoms in Calva and CIDER.

### cider-nrepl version

0.47.1

### Java version

20

### Operating system

MacOS

**Comment by PEZ** [comment]
It's been brought to my attention that `[3 1]` is indeed the right `coor` for the dereffed atom. This needs to be fixed in Calva instead.

**Comment by bbatsov** [comment]
A problem that solves itself! My favorite kind! 😄

**Comment by vemv** [comment]
Let us know if the documentation could be improved somewhere

Cheers - V
